# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(help_text='Unique license number', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('professional_medical', 'Licence Médicale Professionnelle'), ('professional_pharmacy', 'Licence Pharmacie Professionnelle'), ('professional_nursing', 'Licence Infirmier Professionnelle'), ('professional_lab_tech', 'Licence Technicien Laboratoire'), ('organization_hospital', 'Licence Exploitation Hôpital'), ('organization_pharmacy', 'Licence Exploitation Pharmacie'), ('organization_clinic', 'Licence Exploitation Clinique'), ('software', 'Licence Logiciel'), ('equipment_medical', 'Licence Équipement Médical'), ('controlled_substances', 'Licence Substances Contrôlées')], help_text='Type of license', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('revoked', 'Révoqué'), ('pending', "En Attente d'Approbation"), ('renewal_required', 'Renouvellement Requis')], default='active', help_text='Current license status', max_length=50)),
                ('issuing_authority', models.CharField(help_text='Authority that issued the license', max_length=200)),
                ('issued_date', models.DateField(help_text='Date license was issued')),
                ('expiry_date', models.DateField(help_text='Date license expires')),
                ('renewal_date', models.DateField(blank=True, help_text='Next renewal date (if different from expiry)', null=True)),
                ('title', models.CharField(help_text='License title/name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='License description')),
                ('scope_of_practice', models.TextField(blank=True, help_text='Scope of practice or permitted activities')),
                ('conditions', models.TextField(blank=True, help_text='Special conditions or restrictions')),
                ('renewal_required', models.BooleanField(default=True, help_text='Whether license requires periodic renewal')),
                ('renewal_period_months', models.PositiveIntegerField(blank=True, help_text='Renewal period in months', null=True)),
                ('ceu_required', models.BooleanField(default=False, help_text='Continuing Education Units required for renewal')),
                ('ceu_hours_required', models.PositiveIntegerField(blank=True, help_text='CEU hours required for renewal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional license data')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL)),
                ('holder_organization', models.ForeignKey(blank=True, help_text='Organization holding this license', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='organizations.organization')),
                ('holder_user', models.ForeignKey(blank=True, help_text='User holding this license (for professional licenses)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'db_table': 'licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renewal_date', models.DateField()),
                ('new_expiry_date', models.DateField()),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ceu_hours_completed', models.PositiveIntegerField(blank=True, help_text='CEU hours completed for this renewal', null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='licenses.license')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renouvellement de Licence',
                'verbose_name_plural': 'Renouvellements de Licence',
                'db_table': 'license_renewals',
                'ordering': ['-renewal_date'],
            },
        ),
        migrations.CreateModel(
            name='LicenseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('certificate', 'Certificat'), ('renewal', 'Document de Renouvellement'), ('amendment', 'Amendement'), ('correspondence', 'Correspondance Officielle'), ('inspection_report', "Rapport d'Inspection")], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='license_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='licenses.license')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de Licence',
                'verbose_name_plural': 'Documents de Licence',
                'db_table': 'license_documents',
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_number'], name='licenses_license_09b588_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['type', 'status'], name='licenses_type_e76ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expiry_date'], name='licenses_expiry__b19b7b_idx'),
        ),
    ]
