# Generated by Django 4.2.28 on 2026-02-17 18:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='holder_organization',
        ),
        migrations.RemoveField(
            model_name='license',
            name='holder_user',
        ),
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization holding this license', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date license was issued'),
        ),
        migrations.AlterField(
            model_name='license',
            name='issuing_authority',
            field=models.CharField(default='Ministère de la Santé Publique - RD Congo', help_text='Authority that issued the license', max_length=200),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique license number', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='renewal_period_months',
            field=models.PositiveIntegerField(default=12, help_text='Renewal period in months'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('revoked', 'Révoqué'), ('pending', "En Attente d'Approbation"), ('renewal_required', 'Renouvellement Requis')], default='pending', help_text='Current license status', max_length=50),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(blank=True, help_text='License title/name (auto-generated if empty)', max_length=200),
        ),
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('PHARMACY', 'Pharmacie'), ('HOSPITAL', 'Hôpital'), ('OCCUPATIONAL_HEALTH', 'Santé au Travail'), ('PHARMACY_HOSPITAL', 'Pharmacie + Hôpital'), ('HOSPITAL_OCCUPATIONAL_HEALTH', 'Hôpital + Santé au Travail'), ('COMBINED', 'Combinée (Tous Modules)')], help_text='Type of license', max_length=50),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization'], name='licenses_organiz_6ed57d_idx'),
        ),
    ]
