# Generated by Django 6.0.3 on 2026-04-21 10:08

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_expiration_date'),
        ('organizations', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_blister_selling',
            field=models.BooleanField(default=True, help_text='Autoriser la vente par plaquette'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_unit_selling',
            field=models.BooleanField(default=True, help_text="Autoriser la vente à l'unité (comprimé, gélule...)"),
        ),
        migrations.AddField(
            model_name='product',
            name='blisters_per_box',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de plaquettes par boîte'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_per_blister',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente par plaquette (auto-calculé si vide)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix de vente à l'unité (auto-calculé si vide)", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_blister',
            field=models.PositiveIntegerField(default=10, help_text="Nombre d'unités (comprimés/gélules) par plaquette"),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['inventory_item', 'status', 'expiry_date'], name='inventory_b_invento_aecb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active', 'category'], name='products_organiz_9c8443_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'name'], name='products_organiz_c33e62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_item', 'movement_date'], name='stock_movem_invento_6d89b5_idx'),
        ),
    ]
