# Generated by Django 4.2.28 on 2026-02-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='work_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='occupational_health.worksite'),
        ),
    ]
