# Generated by Django 4.2.28 on 2026-02-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0002_alter_worker_work_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVisitProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('pre_employment', "Visite d'Embauche"), ('periodic', 'Visite Périodique'), ('return_to_work', 'Visite de Reprise'), ('post_incident', 'Visite Post-Accident'), ('fitness_for_duty', 'Aptitude Spécifique'), ('exit_medical', 'Visite de Sortie'), ('special_request', 'Demande Spéciale'), ('pregnancy_related', 'Suivi Grossesse'), ('night_work', 'Aptitude Travail de Nuit')], max_length=30, verbose_name='Type de Visite')),
                ('visit_type_label_override', models.CharField(blank=True, help_text='Laisser vide pour utiliser le libellé par défaut du type de visite', max_length=100, verbose_name='Libellé Personnalisé')),
                ('validity_months', models.PositiveSmallIntegerField(default=12, help_text='Durée de validité du certificat en mois (0 = examen unique non périodique)', verbose_name='Validité (mois)')),
                ('regulatory_note', models.TextField(blank=True, help_text='Ex: Code Minier RDC · ILO C176 · Décret N°18/025', verbose_name='Référence Réglementaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Protocole d'Examen",
                'verbose_name_plural': "Protocoles d'Examens",
                'ordering': ['position__name', 'visit_type'],
            },
        ),
        migrations.CreateModel(
            name='MedicalExamCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifiant unique en MAJUSCULES_UNDERSCORE, ex: RADIO_THORAX', max_length=60, unique=True, verbose_name='Code Examen')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('category', models.CharField(choices=[('clinique', 'Clinique'), ('biologique', 'Biologique'), ('imagerie', 'Imagerie'), ('fonctionnel', 'Fonctionnel'), ('cardiologique', 'Cardiologique'), ('ophtalmologie', 'Ophtalmologie'), ('neurologique', 'Neurologique'), ('toxicologie', 'Toxicologie'), ('psychotechnique', 'Psychotechnique'), ('psychosocial', 'Psychosocial'), ('aptitude', 'Aptitude')], default='clinique', max_length=30, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requires_specialist', models.BooleanField(default=False, help_text='Cocher si cet examen nécessite une référence vers un spécialiste', verbose_name='Spécialiste Requis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogue — Examen Médical',
                'verbose_name_plural': 'Catalogue — Examens Médicaux',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OccDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: MIN_UNDER, MIN_ENGINS, TEL_PYLONE', max_length=30, unique=True, verbose_name='Code Département')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['sector__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolRequiredExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_blocking', models.BooleanField(default=True, help_text="Si coché, la décision d'aptitude ne peut être prise sans ce résultat", verbose_name='Bloquant')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupational_health.medicalexamcatalog', verbose_name='Examen')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occupational_health.examvisitprotocol')),
            ],
            options={
                'verbose_name': 'Examen Requis du Protocole',
                'verbose_name_plural': 'Examens Requis des Protocoles',
                'ordering': ['order'],
                'unique_together': {('protocol', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='OccSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Court code MAJUSCULE, ex: MIN, TEL, BAN', max_length=20, unique=True, verbose_name='Code Secteur')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('industry_sector_key', models.CharField(blank=True, help_text='Correspond au type IndustrySector du frontend (mining, telecom_it, banking_finance…)', max_length=50, verbose_name='Clé Secteur Industrie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectors_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OccPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: FOREUR, CHAUFFEUR_MINE, TECH_HAUTEUR', max_length=40, unique=True, verbose_name='Code Poste')),
                ('name', models.CharField(max_length=200, verbose_name='Intitulé du Poste')),
                ('typical_exposures', models.JSONField(blank=True, default=list, help_text='Liste de codes ExposureRisk, ex: ["silica_dust", "noise"]', verbose_name='Expositions Typiques')),
                ('recommended_ppe', models.JSONField(blank=True, default=list, help_text='Liste de codes PPEType, ex: ["hard_hat", "ear_plugs"]', verbose_name='EPI Recommandés')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='occupational_health.occdepartment', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['department__sector__name', 'department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='occdepartment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='occupational_health.occsector', verbose_name='Secteur'),
        ),
        migrations.AddField(
            model_name='examvisitprotocol',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='occupational_health.occposition', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='examvisitprotocol',
            name='recommended_exams',
            field=models.ManyToManyField(blank=True, related_name='recommended_in_protocols', to='occupational_health.medicalexamcatalog', verbose_name='Examens Recommandés'),
        ),
        migrations.AddField(
            model_name='examvisitprotocol',
            name='required_exams',
            field=models.ManyToManyField(blank=True, related_name='required_in_protocols', through='occupational_health.ProtocolRequiredExam', to='occupational_health.medicalexamcatalog', verbose_name='Examens Obligatoires'),
        ),
        migrations.AddField(
            model_name='worker',
            name='occ_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='occupational_health.occdepartment', verbose_name='Département (Protocoles)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='occ_position',
            field=models.ForeignKey(blank=True, help_text="Lie ce travailleur aux protocoles d'examens de ce poste", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='occupational_health.occposition', verbose_name='Poste (Protocoles)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='occ_sector',
            field=models.ForeignKey(blank=True, help_text="Secteur structuré pour l'auto-sélection des protocoles d'examen", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='occupational_health.occsector', verbose_name='Secteur (Protocoles)'),
        ),
        migrations.AlterUniqueTogether(
            name='examvisitprotocol',
            unique_together={('position', 'visit_type')},
        ),
    ]
