# Generated by Django 4.2.28 on 2026-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0003_protocol_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, verbose_name='Contact Urgence Tél'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone Site'),
        ),
    ]
