# Generated by Django 4.2.28 on 2026-02-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0004_phone_max_length_20'),
        ('occupational_health', '0004_risk_assessment_features'),
    ]

    operations = [
    ]
