# Generated by Django 4.2.28 on 2026-02-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0007_surveillanceprogram_surveillanceenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_type', models.CharField(choices=[('ergonomic', 'Ergonomic Assessment'), ('mental', 'Mental Health Screening'), ('cardio', 'Cardiovascular Risk Assessment'), ('msk', 'Musculoskeletal Screening')], max_length=20)),
                ('responses', models.JSONField(default=dict, help_text='Flexible JSON storage for screening responses')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_screenings_conducted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_screenings_reviewed', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_screenings', to='occupational_health.worker')),
            ],
            options={
                'verbose_name': 'Health Screening',
                'verbose_name_plural': 'Health Screenings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['worker', 'screening_type'], name='occupationa_worker__04fc19_idx'), models.Index(fields=['created_at'], name='occupationa_created_fdea32_idx')],
            },
        ),
    ]
