# Generated by Django 4.2.28 on 2026-02-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0002_occconsultation'),
        ('occupational_health', '0008_healthscreening'),
    ]

    operations = [
    ]
