# Generated by Django 4.2.28 on 2026-02-27 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0009_merge_0002_occconsultation_0008_healthscreening'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=20, verbose_name='Type')),
                ('file', models.FileField(help_text='Image (JPEG, PNG) or Video (MP4, WebM)', upload_to='incidents/%Y/%m/%d/', verbose_name='Fichier')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail for videos', null=True, upload_to='incidents/thumbnails/%Y/%m/%d/', verbose_name='Aperçu')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille Fichier (bytes)')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='For videos', null=True, verbose_name='Durée (secondes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('mime_type', models.CharField(blank=True, max_length=50, verbose_name='Type MIME')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Upload')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Pièce jointe Incident',
                'verbose_name_plural': 'Pièces jointes Incidents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='occconsultation',
            name='occupational_worker_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='occconsultation',
            name='occupational_doctor_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='occconsultation',
            name='occupational_created_at_idx',
        ),
        migrations.AlterIndexTogether(
            name='occconsultation',
            index_together={('created_at',), ('doctor', 'status'), ('worker', 'status')},
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='occupational_health.workplaceincident'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incidentattachment',
            index=models.Index(fields=['incident', '-uploaded_at'], name='occupationa_inciden_00ee76_idx'),
        ),
    ]
