# Generated by Django 4.2.28 on 2026-03-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0008_add_updated_by_surveillance'),
        ('occupational_health', '0010_incidentattachment_and_more'),
    ]

    operations = [
    ]
