# Generated by Django 4.2.28 on 2026-03-01 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0011_merge_20260301_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillanceprogram',
            name='coverage_percentage',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Couverture Cible (%)'),
        ),
        migrations.AddField(
            model_name='surveillanceprogram',
            name='follow_up_procedures',
            field=models.TextField(blank=True, help_text='Actions de suivi requises pour les résultats anormaux', verbose_name='Procédures Suivi'),
        ),
        migrations.AddField(
            model_name='surveillanceprogram',
            name='medical_protocols',
            field=models.TextField(blank=True, help_text='Description des protocoles médicaux à suivre', verbose_name='Protocoles Médicaux'),
        ),
        migrations.AddField(
            model_name='surveillanceprogram',
            name='risk_assessment_method',
            field=models.TextField(blank=True, help_text='Approche utilisée pour évaluer les risques', verbose_name='Méthodologie Évaluation Risques'),
        ),
        migrations.AddField(
            model_name='surveillanceprogram',
            name='target_job_categories',
            field=models.JSONField(blank=True, default=list, help_text="Liste des catégories d'emploi: ['underground_work', 'surface_operations']", verbose_name='Catégories Emploi Ciblées'),
        ),
    ]
