# Generated by Django 4.2.28 on 2026-03-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0012_add_surveillance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardidentification',
            name='responsible_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_hazards', to='occupational_health.worker', verbose_name='Personne Responsable'),
        ),
    ]
