# Generated by Django 4.2.28 on 2026-03-02 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0013_hazardidentification_responsible_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardidentification',
            name='responsible_worker',
        ),
        migrations.AddField(
            model_name='hazardidentification',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='Personne Responsable'),
        ),
    ]
