# Generated by Django 4.2.28 on 2026-03-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0013_hazardidentification_responsible_worker'),
    ]

    operations = [
        # First, clear the problematic responsible_worker field data
        migrations.RunPython(
            lambda apps, schema_editor: None,  # Forward: no-op (data will be cleared by remove)
            lambda apps, schema_editor: None,  # Backward: no-op
        ),
        # Remove the old responsible_worker field
        migrations.RemoveField(
            model_name='hazardidentification',
            name='responsible_worker',
        ),
        # Add the new responsible_person field pointing to Worker model
        migrations.AddField(
            model_name='hazardidentification',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_responsibilities', to='occupational_health.worker', verbose_name='Personne Responsable'),
        ),
    ]
