# Generated by Django 4.2.28 on 2026-03-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0014_remove_hazardidentification_responsible_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardidentification',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_responsibilities', to='occupational_health.worker', verbose_name='Personne Responsable'),
        ),
    ]
