# Generated by Django 4.2.28 on 2026-03-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0015_alter_hazardidentification_responsible_person'),
    ]

    operations = [
    ]
