# Generated by Django 4.2.28 on 2026-03-04 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0015_workplaceincident_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardidentification',
            name='status_history',
            field=models.JSONField(default=list, help_text='Track all status changes: [{status, changed_by_id, changed_by_name, changed_at, note}, ...]'),
        ),
        migrations.AddField(
            model_name='hazardidentification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
