# Generated by Django 4.2.28 on 2026-03-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0016_hazardidentification_status_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardidentification',
            name='activities_affected',
            field=models.TextField(blank=True, verbose_name='Activités Affectées'),
        ),
        migrations.AlterField(
            model_name='hazardidentification',
            name='existing_controls',
            field=models.TextField(blank=True, verbose_name='Contrôles Existants'),
        ),
    ]
