# Generated by Django 4.2.28 on 2026-03-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0018_fix_responsible_person_fk_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplaceincident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workplaceincident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workplaceincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PPECatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppe_type', models.CharField(choices=[('hard_hat', 'Casque de Sécurité'), ('safety_glasses', 'Lunettes Sécurité'), ('hearing_protection', 'Protection Auditive'), ('respirator', 'Appareil Respiratoire'), ('face_mask', 'Masque Facial'), ('gloves', 'Gants'), ('steel_toe_boots', 'Chaussures Sécurité'), ('harness', 'Harnais'), ('reflective_vest', 'Gilet Réfléchissant'), ('chemical_suit', 'Combinaison Chimique'), ('lab_coat', 'Blouse Laboratoire'), ('face_shield', 'Écran Facial'), ('radiation_badge', 'Badge Radiation'), ('ergonomic_chair', 'Chaise Ergonomique'), ('wrist_rest', 'Repose-Poignet'), ('sun_protection', 'Protection Solaire'), ('boots', 'Bottes'), ('none_required', 'Aucun PPE Requis')], max_length=50, verbose_name='Type PPE')),
                ('category', models.CharField(choices=[('head', 'Protection Tête'), ('eye', 'Protection Yeux'), ('ear', 'Protection Auditive'), ('respiratory', 'Protection Respiratoire'), ('hand', 'Protection Mains'), ('foot', 'Protection Pieds'), ('body', 'Protection Corps'), ('fall', 'Protection Anti-chute'), ('high_vis', 'Haute Visibilité'), ('chemical', 'Protection Chimique'), ('electrical', 'Protection Électrique'), ('thermal', 'Protection Thermique'), ('ergonomic', 'Ergonomique'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Modèle / Référence')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de Pièce')),
                ('colour_size', models.CharField(blank=True, help_text='Ex: Rouge, Taille L/XL', max_length=100, verbose_name='Couleur / Taille')),
                ('certification_standard', models.CharField(blank=True, help_text='Ex: EN 397:2012, ANSI Z87.1', max_length=200, verbose_name='Norme Certification')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro Certificat')),
                ('certification_body', models.CharField(blank=True, max_length=200, verbose_name='Organisme Certificateur')),
                ('certification_expiry', models.DateField(blank=True, null=True, verbose_name='Expiration Certification')),
                ('risk_protection_level', models.CharField(blank=True, choices=[('basic', 'Protection Basique'), ('intermediate', 'Protection Intermédiaire'), ('advanced', 'Protection Avancée'), ('specialist', 'Spécialiste')], max_length=20, verbose_name='Niveau Protection')),
                ('compatible_hazard_types', models.JSONField(blank=True, default=list, help_text='List of hazard_type values this PPE protects against', verbose_name='Types Dangers Compatibles')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité en Stock')),
                ('assigned_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité Attribuée')),
                ('minimum_stock_level', models.PositiveIntegerField(default=10, verbose_name='Stock Minimum')),
                ('reorder_point', models.PositiveIntegerField(default=20, verbose_name='Point Réapprovisionnement')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='Lieu de Stockage')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de Lot')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Date de Fabrication')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'Expiration / Péremption")),
                ('max_lifespan_months', models.PositiveIntegerField(blank=True, help_text='Maximum service life in months from issue date', null=True, verbose_name='Durée de Vie Max (mois)')),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalle Maintenance (mois)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix Unitaire')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='Devise')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('supplier_contact', models.CharField(blank=True, max_length=200, verbose_name='Contact Fournisseur')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence Fournisseur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_catalog_created', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_catalog', to='occupational_health.enterprise')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_catalog_updated', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_catalog', to='occupational_health.worksite')),
            ],
            options={
                'verbose_name': 'Catalogue EPI',
                'verbose_name_plural': 'Catalogue EPI',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PPEAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppe_item_name', models.CharField(help_text='Snapshot at time of action', max_length=200, verbose_name='Nom EPI')),
                ('action', models.CharField(choices=[('created', 'Créé'), ('updated', 'Modifié'), ('deleted', 'Supprimé'), ('stock_added', 'Stock Ajouté'), ('stock_removed', 'Stock Retiré'), ('assigned', 'Attribué'), ('returned', 'Retourné'), ('inspected', 'Inspecté'), ('deactivated', 'Désactivé'), ('reactivated', 'Réactivé')], max_length=30, verbose_name='Action')),
                ('actor_name', models.CharField(blank=True, help_text='Snapshot of actor name', max_length=200, verbose_name='Acteur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{field: {old, new}} for updates', verbose_name='Modifications')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('worker_name', models.CharField(blank=True, max_length=200, verbose_name='Travailleur')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('ppe_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='occupational_health.ppecatalog')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_audit_logs', to='occupational_health.worker')),
            ],
            options={
                'verbose_name': 'Journal Audit EPI',
                'verbose_name_plural': 'Journal Audit EPI',
                'ordering': ['-timestamp'],
            },
        ),
    ]
