# Generated by Django 4.2.28 on 2026-03-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0021_exposure_reading_worker_nullable_datefield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exposurereading',
            new_name='occupationa_worker__b03d0c_idx',
            old_name='occupational_worker_measure_idx',
        ),
        migrations.RenameIndex(
            model_name='exposurereading',
            new_name='occupationa_enterpr_5effcf_idx',
            old_name='occupational_enter_expo_idx',
        ),
        migrations.RenameIndex(
            model_name='exposurereading',
            new_name='occupationa_status_fa8161_idx',
            old_name='occupational_status_date_idx',
        ),
    ]
