# Generated by Django 4.2.28 on 2026-03-04 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0023_consultation_occupational_history_and_fitness_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesscertificate',
            name='restrictions',
            field=models.TextField(blank=True, help_text='Ex: pas de travail en hauteur, poste adapté', verbose_name='Restrictions (libre)'),
        ),
        migrations.CreateModel(
            name='RiskProfileAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('calculated', 'Calculé'), ('recalculated', 'Recalculé'), ('updated', 'Modifié'), ('trigger_medical', 'Déclenché - Examen'), ('trigger_fitness', 'Déclenché - Aptitude'), ('trigger_incident', 'Déclenché - Incident'), ('trigger_disease', 'Déclenché - Maladie')], max_length=30, verbose_name='Action')),
                ('trigger_type', models.CharField(blank=True, choices=[('medical_examination', 'Examen médical'), ('fitness_certificate', "Certificat d'aptitude"), ('workplace_incident', 'Incident sur le lieu de travail'), ('occupational_disease', 'Maladie professionnelle'), ('manual_calculation', 'Calcul manuel (API)'), ('scheduled_task', 'Tâche planifiée'), ('other', 'Autre')], max_length=30, verbose_name='Type de déclencheur')),
                ('trigger_id', models.IntegerField(blank=True, help_text='ID of the related object (exam, incident, etc)', null=True, verbose_name='ID du déclencheur')),
                ('health_risk_before', models.PositiveIntegerField(default=0)),
                ('health_risk_after', models.PositiveIntegerField(default=0)),
                ('exposure_risk_before', models.PositiveIntegerField(default=0)),
                ('exposure_risk_after', models.PositiveIntegerField(default=0)),
                ('compliance_risk_before', models.PositiveIntegerField(default=0)),
                ('compliance_risk_after', models.PositiveIntegerField(default=0)),
                ('overall_risk_before', models.PositiveIntegerField(default=0)),
                ('overall_risk_after', models.PositiveIntegerField(default=0)),
                ('risk_level_before', models.CharField(blank=True, max_length=20)),
                ('risk_level_after', models.CharField(blank=True, max_length=20)),
                ('actor_name', models.CharField(blank=True, help_text='Snapshot of actor name', max_length=200, verbose_name='Acteur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('reason_for_change', models.TextField(blank=True, verbose_name='Raison du changement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('is_automatic', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_profile_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile_audits', to='occupational_health.worker')),
                ('worker_risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='occupational_health.workerriskprofile')),
            ],
            options={
                'verbose_name': 'Risk Profile Audit Log',
                'verbose_name_plural': 'Risk Profile Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['worker', '-timestamp'], name='occupationa_worker__b78ae0_idx'), models.Index(fields=['trigger_type', '-timestamp'], name='occupationa_trigger_9247c2_idx')],
            },
        ),
    ]
