# Generated by Django 4.2.28 on 2026-03-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0024_add_risk_profile_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureTypeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_type', models.CharField(choices=[('silica_dust', 'Crystalline Silica (Respirable)'), ('cobalt', 'Cobalt & Compounds'), ('total_dust', 'Total Inhalable Dust'), ('noise', 'Noise Level'), ('vibration', 'Hand-Arm Vibration'), ('heat', 'Wet Bulb Globe Temperature (WBGT)'), ('lead', 'Lead & Compounds'), ('asbestos', 'Asbestos Fibers'), ('chemical', 'Chemical Vapor'), ('biological', 'Biological Agents')], max_length=50, unique=True)),
                ('osha_twa_limit', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Limite OSHA TWA')),
                ('acgih_tlv_limit', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Limite ACGIH TLV')),
                ('local_limit', models.DecimalField(decimal_places=3, help_text='Default DRC/Congo local limit', max_digits=10, verbose_name='Limite Locale (DRC)')),
                ('unit_measurement', models.CharField(help_text='e.g., mg/m³, µg/m³, dB(A)', max_length=20, verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Exposure Type Limit',
                'verbose_name_plural': 'Exposure Type Limits',
                'ordering': ['exposure_type'],
            },
        ),
    ]
