# Generated by Django 4.2.28 on 2026-03-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0025_exposuretypelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='overexposurealert',
            name='area_location',
            field=models.CharField(blank=True, help_text='e.g., Mining Shaft A, Grinding Mill', max_length=200),
        ),
        migrations.AddField(
            model_name='overexposurealert',
            name='monitoring_type',
            field=models.CharField(blank=True, help_text='environmental, area, ambient', max_length=50),
        ),
        migrations.AlterField(
            model_name='overexposurealert',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Leave blank for area monitoring alerts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overexposure_alerts', to='occupational_health.worker'),
        ),
    ]
