# Generated by Django 4.2.28 on 2026-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0026_overexposurealert_area_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overexposurealert',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True when auto-triggered from an ExposureReading measurement'),
        ),
        migrations.AddField(
            model_name='overexposurealert',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal CAPA comments and investigation notes'),
        ),
        migrations.AddIndex(
            model_name='overexposurealert',
            index=models.Index(fields=['worker', '-detected_date'], name='occupationa_worker__8ee42e_idx'),
        ),
        migrations.AddIndex(
            model_name='overexposurealert',
            index=models.Index(fields=['severity', 'status', '-detected_date'], name='occupationa_severit_019942_idx'),
        ),
    ]
