# Generated by Django 4.2.28 on 2026-03-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occupational_health', '0032_ppecompliancerecord_worker_ppecatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexamination',
            name='examining_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppecatalog',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppe_catalog', to='occupational_health.enterprise'),
        ),
        migrations.AlterField(
            model_name='ppecompliancerecord',
            name='check_date',
            field=models.DateField(verbose_name='Date Vérification'),
        ),
        migrations.AlterField(
            model_name='ppecompliancerecord',
            name='condition_notes',
            field=models.TextField(blank=True, verbose_name='Notes État'),
        ),
        migrations.AlterField(
            model_name='ppecompliancerecord',
            name='corrective_action',
            field=models.TextField(blank=True, verbose_name='Action Corrective'),
        ),
        migrations.AlterField(
            model_name='ppecompliancerecord',
            name='corrective_action_required',
            field=models.BooleanField(default=False, verbose_name='Action Corrective Requise'),
        ),
        migrations.AlterField(
            model_name='ppecompliancerecord',
            name='is_compliant',
            field=models.BooleanField(default=True, verbose_name='Conforme'),
        ),
        migrations.AlterField(
            model_name='ppecompliancerecord',
            name='non_compliance_reason',
            field=models.TextField(blank=True, verbose_name='Raison Non-Conformité'),
        ),
    ]
