# Generated by Django 4.2.28 on 2026-03-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0035_add_national_id_spinal_xray_mining_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='drcregulatoryreport',
            name='accident_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date/heure de l'accident"),
        ),
        migrations.AddField(
            model_name='drcregulatoryreport',
            name='declaration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Délai légal de déclaration'),
        ),
        migrations.AddField(
            model_name='drcregulatoryreport',
            name='itm_inspection_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence ITM'),
        ),
        migrations.AddField(
            model_name='drcregulatoryreport',
            name='itm_office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bureau ITM'),
        ),
        migrations.AddField(
            model_name='drcregulatoryreport',
            name='workers_affected_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nb. travailleurs affectés'),
        ),
        migrations.AlterField(
            model_name='drcregulatoryreport',
            name='report_type',
            field=models.CharField(choices=[('work_accident_declaration', 'Work Accident Declaration (AT)'), ('monthly_incident', 'Monthly Incidents'), ('quarterly_health', 'Quarterly Health'), ('annual_compliance', 'Annual Compliance'), ('annual_pamt', 'Plan Annuel de Médecine du Travail (PAMT)'), ('fatal_incident', 'Fatal Incident'), ('severe_incident', 'Severe Incident'), ('occupational_disease_notice', 'Disease Notice')], max_length=100),
        ),
    ]
