# Generated by Django 4.2.28 on 2026-03-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupational_health', '0036_drcregulatoryreport_accident_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('iso_45001', 'ISO 45001'), ('ilo', 'ILO Conventions'), ('national', 'National Law'), ('sectoral', 'Sector Specific'), ('internal', 'Internal Standards')], max_length=20)),
                ('standard_name', models.CharField(help_text='e.g., ISO 45001, ILO-C190', max_length=200)),
                ('clause_reference', models.CharField(blank=True, help_text='e.g., Section 5.2', max_length=100)),
                ('requirement_text', models.TextField()),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('partial', 'Partial Compliance'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable')], default='partial', max_length=20)),
                ('evidence_document', models.TextField(blank=True, help_text='Description of evidence demonstrating compliance')),
                ('responsible_department', models.CharField(blank=True, max_length=200)),
                ('responsible_person', models.CharField(blank=True, max_length=200)),
                ('identified_date', models.DateField(auto_now_add=True)),
                ('implementation_deadline', models.DateField(blank=True, null=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('audit_findings', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_requirements', to='occupational_health.enterprise')),
            ],
            options={
                'verbose_name': 'Regulatory Requirement',
                'verbose_name_plural': 'Regulatory Requirements',
                'ordering': ['category', 'requirement_id'],
                'unique_together': {('enterprise', 'requirement_id')},
            },
        ),
    ]
