/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Roboto"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
      },
      colors: {
        primary: '#122056',
        primaryLight: '#1E3A8A',
        primaryDark: '#0F1B42',
        primaryFaded: 'rgba(18, 32, 86, 0.08)',
        secondary: '#5B65DC',
        secondaryLight: '#818CF8',
        secondaryDark: '#4338CA',
        accent: '#818CF8',
        accentLight: '#A5B4FC',
        accentDark: '#5B65DC',
        sidebar: '#0F1B42',
        sidebarHover: '#1E3A8A',
        sidebarText: '#94A3B8',
        sidebarTextActive: '#FFFFFF',
        success: '#5B65DC',
        successLight: '#E0E7FF',
        successDark: '#4338CA',
        error: '#EF4444',
        errorLight: '#FEE2E2',
        errorDark: '#DC2626',
        warning: '#F59E0B',
        warningLight: '#FEF3C7',
        warningDark: '#D97706',
        info: '#818CF8',
        infoLight: '#E0E7FF',
        infoDark: '#6366F1',
        surface: '#FFFFFF',
        surfaceVariant: '#F1F5F9',
        background: '#FAFAFD',
        outline: '#E2E8F0',
        outlineVariant: '#F1F5F9',
        onSurface: '#0F172A',
        onSurfaceVariant: '#64748B',
        onBackground: '#0F172A',
        text: '#0F172A',
        textSecondary: '#64748B',
        textTertiary: '#94A3B8',
      },
    },
  },
  plugins: [],
}
