# Generated by Django 4.2.28 on 2026-02-17 12:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de consultation')),
                ('encounter_type', models.CharField(choices=[('outpatient', 'Consultation externe'), ('inpatient', 'Hospitalisation'), ('emergency', 'Urgence'), ('icu', 'Soins intensifs'), ('surgery', 'Chirurgie'), ('dialysis', 'Dialyse'), ('rehabilitation', 'Rééducation'), ('maternity', 'Maternité')], default='outpatient', max_length=20, verbose_name='Type de consultation')),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('checked_in', 'Enregistré'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Motif de consultation')),
                ('history_of_present_illness', models.TextField(blank=True, verbose_name='Histoire de la maladie')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de chambre')),
                ('bed_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de lit')),
                ('referred_by', models.CharField(blank=True, max_length=200, verbose_name='Référé par')),
                ('referred_to', models.CharField(blank=True, max_length=200, verbose_name='Référé vers')),
                ('admission_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'admission")),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût estimé')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('attending_physician', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_encounters', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hospital_encounters', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('nursing_staff', models.ManyToManyField(blank=True, limit_choices_to={'user_type__in': ['nurse', 'nursing_aide']}, related_name='nursing_encounters', to=settings.AUTH_USER_MODEL, verbose_name='Personnel soignant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_encounters', to='organizations.organization', verbose_name='Établissement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_encounters', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hospital_encounters', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Consultation hospitalière',
                'verbose_name_plural': 'Consultations hospitalières',
                'db_table': 'hospital_encounters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='En degrés Celsius (30.0 - 50.0)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(50.0)], verbose_name='Température (°C)')),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, help_text='Pression artérielle systolique (50-300 mmHg)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)], verbose_name='Tension systolique (mmHg)')),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, help_text='Pression artérielle diastolique (30-200 mmHg)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Tension diastolique (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='Battements par minute (30-250 bpm)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Fréquence cardiaque (bpm)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='Respirations par minute (5-60 /min)', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='Fréquence respiratoire (/min)')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, help_text='Saturation en oxygène (50-100%)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Saturation O₂ (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='En kilogrammes (0.5-500.0 kg)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('500.0'))], verbose_name='Poids (kg)')),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='En centimètres (30-250 cm)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Taille (cm)')),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, help_text='Échelle de douleur de 0 (aucune) à 10 (intense)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Niveau de douleur (0-10)')),
                ('blood_glucose', models.PositiveSmallIntegerField(blank=True, help_text='En mg/dL (20-800)', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(800)], verbose_name='Glycémie (mg/dL)')),
                ('body_mass_index', models.DecimalField(blank=True, decimal_places=1, help_text='Calculé automatiquement à partir du poids et de la taille', max_digits=4, null=True, verbose_name='IMC calculé')),
                ('measurement_location', models.CharField(blank=True, help_text='Service, chambre, ou lieu où les signes vitaux ont été pris', max_length=100, verbose_name='Lieu de mesure')),
                ('measurement_method', models.CharField(blank=True, help_text='Équipement ou méthode utilisée', max_length=100, verbose_name='Méthode de mesure')),
                ('clinical_notes', models.TextField(blank=True, help_text='Observations ou remarques sur les signes vitaux', verbose_name='Notes cliniques')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Mesuré le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vital_signs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='hospital.hospitalencounter', verbose_name='Consultation')),
                ('measured_by', models.ForeignKey(limit_choices_to={'user_type__in': ['doctor', 'nurse', 'nursing_aide']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_vital_signs', to=settings.AUTH_USER_MODEL, verbose_name='Mesuré par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vital_signs', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vital_signs', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Signes vitaux',
                'verbose_name_plural': 'Signes vitaux',
                'db_table': 'vital_signs',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='Poste')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Étage')),
                ('bed_capacity', models.PositiveIntegerField(default=0, help_text='Nombre total de lits disponibles', verbose_name='Capacité en lits')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('department_head', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Chef de service')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_departments', to='organizations.organization', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Service hospitalier',
                'verbose_name_plural': 'Services hospitaliers',
                'db_table': 'hospital_departments',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20, verbose_name='Numéro de lit')),
                ('room_number', models.CharField(max_length=20, verbose_name='Numéro de chambre')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupé'), ('reserved', 'Réservé'), ('out_of_order', 'Hors service'), ('cleaning', 'En nettoyage')], default='available', max_length=20, verbose_name='Statut')),
                ('bed_type', models.CharField(blank=True, help_text='Standard, ICU, Maternity, etc.', max_length=50, verbose_name='Type de lit')),
                ('has_cardiac_monitor', models.BooleanField(default=False, verbose_name='Moniteur cardiaque')),
                ('has_oxygen_supply', models.BooleanField(default=False, verbose_name='Oxygène')),
                ('has_suction', models.BooleanField(default=False, verbose_name='Aspiration')),
                ('last_cleaned', models.DateTimeField(blank=True, null=True, verbose_name='Dernière désinfection')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('current_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bed', to='hospital.hospitalencounter', verbose_name='Consultation actuelle')),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bed', to='patients.patient', verbose_name='Patient actuel')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hospital.hospitaldepartment', verbose_name='Service')),
            ],
            options={
                'verbose_name': "Lit d'hôpital",
                'verbose_name_plural': "Lits d'hôpital",
                'db_table': 'hospital_beds',
                'ordering': ['department', 'room_number', 'bed_number'],
                'unique_together': {('department', 'bed_number')},
            },
        ),
    ]
