# Generated by Django 4.2.28 on 2026-02-23 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triage_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de triage')),
                ('triage_date', models.DateTimeField(auto_now_add=True, verbose_name='Date du triage')),
                ('triage_level', models.IntegerField(choices=[(1, 'Réanimation'), (2, 'Urgence'), (3, 'Urgent'), (4, 'Moins urgent'), (5, 'Non urgent')], default=3, verbose_name='Niveau de triage')),
                ('triage_category', models.CharField(blank=True, max_length=50, verbose_name='Catégorie')),
                ('chief_complaint', models.TextField(verbose_name='Plainte principale')),
                ('symptom_onset', models.CharField(blank=True, max_length=100, verbose_name='Début des symptômes')),
                ('acuity', models.CharField(blank=True, max_length=50, verbose_name='Acuité')),
                ('vitals', models.JSONField(blank=True, default=dict, verbose_name='Signes vitaux')),
                ('pain_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Niveau de douleur')),
                ('consciousness_level', models.CharField(blank=True, max_length=50, verbose_name='Niveau de conscience')),
                ('airway_status', models.CharField(blank=True, max_length=50, verbose_name='Statut des voies aériennes')),
                ('breathing_status', models.CharField(blank=True, max_length=50, verbose_name='Statut respiratoire')),
                ('circulation_status', models.CharField(blank=True, max_length=50, verbose_name='Statut circulatoire')),
                ('mobility_status', models.CharField(blank=True, max_length=50, verbose_name='Statut de mobilité')),
                ('red_flags', models.JSONField(blank=True, default=list, verbose_name="Signaux d'alarme")),
                ('has_red_flags', models.BooleanField(default=False, verbose_name="Présente des signaux d'alarme")),
                ('is_trauma', models.BooleanField(default=False, verbose_name='Traumatisme')),
                ('fever_screening', models.BooleanField(default=False, verbose_name='Dépistage fièvre')),
                ('respiratory_symptoms', models.BooleanField(default=False, verbose_name='Symptômes respiratoires')),
                ('isolation_required', models.BooleanField(default=False, verbose_name='Isolement requis')),
                ('allergies_verified', models.BooleanField(default=False, verbose_name='Allergies vérifiées')),
                ('immunocompromised', models.BooleanField(default=False, verbose_name='Immunodéprimé')),
                ('assigned_area', models.CharField(blank=True, max_length=200, verbose_name='Zone assignée')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'En attente'), ('in_treatment', 'En traitement'), ('reassessment_needed', 'Réévaluation'), ('discharged', 'Sorti'), ('admitted', 'Hospitalisé'), ('transferred', 'Transféré'), ('left_before_seen', 'Parti'), ('left_against_advice', 'Parti (AMA)')], default='in_progress', max_length=50, verbose_name='Statut')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('triage_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Début du triage')),
                ('triage_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin du triage')),
                ('estimated_wait_time', models.IntegerField(blank=True, null=True, verbose_name="Temps d'attente estimé (min)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin assigné')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages', to='hospital.hospitalencounter', verbose_name='Consultation')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_performed', to=settings.AUTH_USER_MODEL, verbose_name='Infirmière')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triages', to='organizations.organization', verbose_name='Établissement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triages', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Triage',
                'verbose_name_plural': 'Triages',
                'db_table': 'hospital_triages',
                'ordering': ['-triage_date', 'triage_level'],
                'indexes': [models.Index(fields=['patient', '-triage_date'], name='hospital_tr_patient_7e1132_idx'), models.Index(fields=['triage_level', '-triage_date'], name='hospital_tr_triage__e9a407_idx'), models.Index(fields=['status', '-triage_date'], name='hospital_tr_status_f555a6_idx')],
            },
        ),
    ]
