import { Patient } from '../../models/Patient';
import { OccupationalHealthPatient, IndustrySector, JobCategory, ShiftPattern, FitnessStatus, ExposureRisk, PPEType, SectorRiskLevel } from '../../models/OccupationalHealth';
import { Encounter, EncounterType } from '../../models/Encounter';
import { Prescription, PrescriptionStatus } from '../../models/Prescription';
import { Sale, PaymentMethod } from '../../models/Sale';
import { Product, ProductCategory, DosageForm, UnitOfMeasure, StorageCondition } from '../../models/Inventory';

// ═══════════════════════════════════════════════════════════════
// COMPREHENSIVE SEED DATA FOR ALL MODULES
// ═══════════════════════════════════════════════════════════════

/**
 * Real-world interconnected data spanning Hospital, Pharmacy, and OccHealth
 * - Same patients across modules with realistic progression
 * - Cross-module workflows (hospital → prescription → dispensing)
 * - Enterprise scenarios with occupational health integration
 */

// ─── REALISTIC PATIENTS WITH CROSS-MODULE PRESENCE ──────────────

export const COMPREHENSIVE_PATIENTS: Patient[] = [
  // Mining sector workers - high-risk occupational health cases
  {
    id: 'PAT-001',
    patientNumber: 'HK-2025-001',
    firstName: 'Kabamba',
    lastName: 'Mutombo',
    dateOfBirth: '1988-03-15',
    gender: 'male',
    phone: '+243 81 234 5678',
    email: 'kabamba.mutombo@gecamines.cd',
    address: 'Av. Lumumba 234, Kolwezi',
    emergencyContactName: 'Marie Mutombo',
    emergencyContactPhone: '+243 85 567 8901',
    emergencyContactRelation: 'spouse',
    registrationDate: '2023-06-01',
    lastVisit: '2025-02-08',
    status: 'active',
    allergies: ['Pénicilline', 'Latex'],
    chronicConditions: ['Silicose légère', 'Hypertension'],
    currentMedications: ['Amlodipine 5mg', 'Bronchodilatateur'],
    bloodType: 'O+',
    weight: 75,
    height: 172,
    // Occupational Health context
    employeeId: 'GCM-0421',
    company: 'Gécamines SA',
    sector: 'mining' as IndustrySector,
    site: 'Mine Kamoto - Niveau -300m',
    department: 'Extraction',
    jobTitle: 'Mineur de fond',
    jobCategory: 'underground_work' as JobCategory,
    shiftPattern: 'rotating' as ShiftPattern,
    hireDate: '2015-06-01',
    contractType: 'permanent',
    fitnessStatus: 'fit_with_restrictions' as FitnessStatus,
    exposureRisks: ['silica_dust', 'noise', 'heat_stress', 'vibration'] as ExposureRisk[],
    ppeRequired: ['hard_hat', 'safety_boots', 'dust_mask', 'safety_glasses'] as PPEType[],
    riskLevel: 'very_high' as SectorRiskLevel,
    medicalExamHistory: [
      { date: '2024-06-01', type: 'annual', result: 'fit_with_restrictions', notes: 'Silicose légère détectée' },
      { date: '2025-02-01', type: 'follow_up', result: 'stable', notes: 'Suivi pneumologie' }
    ],
    createdAt: '2023-06-01',
    updatedAt: '2025-02-08',
  },
  {
    id: 'PAT-002',
    patientNumber: 'HK-2024-032',
    firstName: 'Mwamba',
    lastName: 'Kalala',
    dateOfBirth: '1992-07-22',
    gender: 'female',
    phone: '+243 99 876 5432',
    email: 'mwamba.kalala@rawbank.cd',
    address: 'Av. Kasavubu 45, Lubumbashi',
    emergencyContactName: 'Jean Kalala',
    emergencyContactPhone: '+243 82 345 6789',
    emergencyContactRelation: 'spouse',
    registrationDate: '2024-01-15',
    lastVisit: '2025-02-10',
    status: 'active',
    allergies: [],
    chronicConditions: ['Syndrome du canal carpien', 'Troubles anxieux'],
    currentMedications: ['Ibuprofène 400mg', 'Sertraline 50mg'],
    bloodType: 'A+',
    weight: 62,
    height: 165,
    // Occupational Health context
    employeeId: 'RBK-1087',
    company: 'Rawbank',
    sector: 'banking_finance' as IndustrySector,
    site: 'Agence Principale Lubumbashi',
    department: 'Service Clientèle',
    jobTitle: 'Chargée de Clientèle Senior',
    jobCategory: 'customer_service' as JobCategory,
    shiftPattern: 'regular' as ShiftPattern,
    hireDate: '2019-01-15',
    contractType: 'permanent',
    fitnessStatus: 'fit' as FitnessStatus,
    exposureRisks: ['ergonomic', 'psychosocial', 'vdt_screen'] as ExposureRisk[],
    ppeRequired: ['ergonomic_chair', 'wrist_rest'] as PPEType[],
    riskLevel: 'low' as SectorRiskLevel,
    createdAt: '2024-01-15',
    updatedAt: '2025-02-10',
  },
  {
    id: 'PAT-003',
    patientNumber: 'HK-2023-089',
    firstName: 'Tshisekedi',
    lastName: 'Ilunga',
    dateOfBirth: '1985-11-08',
    gender: 'male',
    phone: '+243 85 555 1234',
    email: 'tshisekedi.ilunga@batiment-congo.cd',
    address: 'Quartier Industriel, Kinshasa',
    emergencyContactName: 'Grace Ilunga',
    emergencyContactPhone: '+243 81 777 9999',
    emergencyContactRelation: 'mother',
    registrationDate: '2023-03-10',
    lastVisit: '2025-02-05',
    status: 'active',
    allergies: [],
    chronicConditions: ['Lombalgie chronique', 'Perte auditive partielle'],
    currentMedications: ['Diclofénac gel', 'Multivitamines'],
    bloodType: 'B+',
    weight: 82,
    height: 178,
    // Occupational Health context
    employeeId: 'BCG-0562',
    company: 'Bâtiment Congo SARL',
    sector: 'construction' as IndustrySector,
    site: 'Chantier Gombe Tower',
    department: 'Charpente Métallique',
    jobTitle: 'Soudeur-Monteur',
    jobCategory: 'construction_trades' as JobCategory,
    shiftPattern: 'day_shift' as ShiftPattern,
    hireDate: '2020-03-10',
    contractType: 'contract',
    fitnessStatus: 'fit_with_restrictions' as FitnessStatus,
    exposureRisks: ['working_at_heights', 'noise', 'chemical_exposure', 'heat_stress'] as ExposureRisk[],
    ppeRequired: ['hard_hat', 'safety_glasses', 'fall_harness', 'safety_boots'] as PPEType[],
    riskLevel: 'very_high' as SectorRiskLevel,
    createdAt: '2023-03-10',
    updatedAt: '2025-02-05',
  },
  {
    id: 'PAT-004',
    patientNumber: 'HK-2024-156',
    firstName: 'Lukusa',
    lastName: 'Nzuzi',
    dateOfBirth: '1995-02-28',
    gender: 'female',
    phone: '+243 82 333 7890',
    email: 'lukusa.nzuzi@hgr-lubumbashi.cd',
    address: 'Av. Mobutu 67, Lubumbashi',
    emergencyContactName: 'Paul Nzuzi',
    emergencyContactPhone: '+243 84 222 3333',
    emergencyContactRelation: 'father',
    registrationDate: '2024-09-01',
    lastVisit: '2025-02-11',
    status: 'active',
    allergies: ['Codéine'],
    chronicConditions: [],
    currentMedications: [],
    bloodType: 'AB+',
    weight: 58,
    height: 160,
    // Occupational Health context
    employeeId: 'HGR-2301',
    company: 'Hôpital Général de Référence',
    sector: 'healthcare' as IndustrySector,
    site: 'HGR Lubumbashi - Bâtiment Central',
    department: 'Soins Infirmiers - Urgences',
    jobTitle: 'Infirmière Urgentiste',
    jobCategory: 'nursing' as JobCategory,
    shiftPattern: 'rotating' as ShiftPattern,
    hireDate: '2021-09-01',
    contractType: 'permanent',
    fitnessStatus: 'fit' as FitnessStatus,
    exposureRisks: ['biological', 'needle_stick', 'psychosocial', 'shift_work'] as ExposureRisk[],
    ppeRequired: ['lab_coat', 'safety_gloves', 'face_shield', 'safety_glasses'] as PPEType[],
    riskLevel: 'high' as SectorRiskLevel,
    vaccinationStatus: [
      { vaccine: 'Hépatite B', date: '2021-09-15', boosterDue: '2026-09-15' },
      { vaccine: 'Tétanos', date: '2024-01-10', boosterDue: '2034-01-10' },
      { vaccine: 'COVID-19', date: '2024-05-20' },
    ],
    createdAt: '2024-09-01',
    updatedAt: '2025-02-11',
  },
  {
    id: 'PAT-005',
    patientNumber: 'HK-2024-203',
    firstName: 'Pongo',
    lastName: 'Tshimanga',
    dateOfBirth: '1990-06-10',
    gender: 'male',
    phone: '+243 81 999 4567',
    email: 'pongo.tshimanga@vodacom.cd',
    address: 'Résidence Gombe, Kinshasa',
    emergencyContactName: 'Sylvie Tshimanga',
    emergencyContactPhone: '+243 99 111 2222',
    emergencyContactRelation: 'spouse',
    registrationDate: '2024-02-01',
    lastVisit: '2025-01-28',
    status: 'active',
    allergies: [],
    chronicConditions: ['Fatigue oculaire digitale', 'Troubles du sommeil'],
    currentMedications: ['Mélatonine 3mg'],
    bloodType: 'O-',
    weight: 70,
    height: 175,
    // Occupational Health context
    employeeId: 'VDC-3412',
    company: 'Vodacom Congo',
    sector: 'telecom_it' as IndustrySector,
    site: 'Kinshasa - Siège Social',
    department: 'Développement Logiciel',
    jobTitle: 'Ingénieur Logiciel Senior',
    jobCategory: 'it_systems' as JobCategory,
    shiftPattern: 'flexible' as ShiftPattern,
    hireDate: '2022-02-01',
    contractType: 'permanent',
    fitnessStatus: 'fit' as FitnessStatus,
    exposureRisks: ['vdt_screen', 'sedentary', 'psychosocial'] as ExposureRisk[],
    ppeRequired: ['ergonomic_chair', 'blue_light_glasses'] as PPEType[],
    riskLevel: 'low' as SectorRiskLevel,
    createdAt: '2024-02-01',
    updatedAt: '2025-01-28',
  },
];

// ─── REALISTIC ENCOUNTERS WITH CROSS-MODULE WORKFLOWS ──────────

export const COMPREHENSIVE_ENCOUNTERS: Encounter[] = [
  // Mining worker - occupational health follow-up → prescription → dispensing
  {
    id: 'ENC-001',
    patientId: 'PAT-001',
    encounterNumber: 'E-2025-001',
    type: 'occupational_health_exam' as EncounterType,
    date: '2025-02-08',
    chiefComplaint: 'Examen périodique obligatoire - Mineur exposé aux poussières de silice',
    presentIllness: 'Toux sèche intermittente depuis 3 mois, aggravée en fin de poste',
    vitalSigns: {
      temperature: 36.8,
      bloodPressure: '145/90',
      heartRate: 78,
      respiratoryRate: 18,
      oxygenSaturation: 96,
    },
    physicalExam: 'Râles crépitants bilatéraux aux bases pulmonaires. Audiométrie révèle perte auditive légère haute fréquence.',
    assessment: 'Silicose débutante confirmée. Hypertension non contrôlée. Perte auditive professionnelle.',
    plan: 'Modification poste de travail. Renforcement EPI. Suivi pneumologue. Traitement hypertension.',
    notes: 'Certificat APTE avec restrictions - Éviter zones haute exposition poussières',
    status: 'discharged',
    doctorId: 'DOC-001',
    doctorName: 'Dr. Kasongo Médecine du Travail',
    facility: 'Centre Médical Gécamines',
    createdAt: '2025-02-08T08:30:00Z',
    updatedAt: '2025-02-08T09:45:00Z',
  },
  // Banking worker - stress-related consultation
  {
    id: 'ENC-002',
    patientId: 'PAT-002',
    encounterNumber: 'E-2025-002',
    type: 'consultation' as EncounterType,
    date: '2025-02-10',
    chiefComplaint: 'Douleurs poignet droit et troubles anxieux liés au travail',
    presentIllness: 'Douleurs poignet persistantes depuis utilisation intensive clavier. Anxiété croissante avec objectifs commerciaux élevés.',
    vitalSigns: {
      temperature: 36.4,
      bloodPressure: '118/75',
      heartRate: 88,
      respiratoryRate: 16,
    },
    physicalExam: 'Test Phalen positif. Tension musculaire cervicale. État anxieux modéré.',
    assessment: 'Syndrome canal carpien confirmé. Troubles anxieux liés au stress professionnel.',
    plan: 'Ergothérapie. Aménagement poste travail. Support psychologique. Traitement anti-inflammatoire.',
    notes: 'Certificat arrêt de travail 5 jours pour aménagement poste',
    status: 'discharged',
    doctorId: 'DOC-002',
    doctorName: 'Dr. Ngoy Médecine Générale',
    facility: 'Clinique Rawbank',
    createdAt: '2025-02-10T14:00:00Z',
    updatedAt: '2025-02-10T14:45:00Z',
  },
  // Construction worker - accident du travail
  {
    id: 'ENC-003',
    patientId: 'PAT-003',
    encounterNumber: 'E-2025-003',
    type: 'emergency' as EncounterType,
    date: '2025-02-05',
    chiefComplaint: 'Chute de 3 mètres - Douleur lombaire intense',
    presentIllness: 'Chute échafaudage ce matin 10h30. Impact sur le dos. Douleur lombaire 8/10.',
    vitalSigns: {
      temperature: 37.1,
      bloodPressure: '160/95',
      heartRate: 105,
      respiratoryRate: 22,
    },
    physicalExam: 'Contracture paravertébrale L3-L5. Mobilité limitée. Réflexes conservés.',
    assessment: 'Lombalgie post-traumatique. Contusion lombaire sans signe neurologique.',
    plan: 'Repos complet 7 jours. Anti-inflammatoires. Kinésithérapie. RDV contrôle.',
    notes: 'ACCIDENT DU TRAVAIL - Déclaration CNSS effectuée',
    status: 'discharged',
    doctorId: 'DOC-003',
    doctorName: 'Dr. Mbala Urgentiste',
    facility: 'Hôpital du Cinquantenaire',
    createdAt: '2025-02-05T11:00:00Z',
    updatedAt: '2025-02-05T12:30:00Z',
  },
  // Healthcare worker - exposition biologique
  {
    id: 'ENC-004',
    patientId: 'PAT-004',
    encounterNumber: 'E-2025-004',
    type: 'occupational_health_exam' as EncounterType,
    date: '2025-02-11',
    chiefComplaint: 'Accident exposition sanguine - Piqûre accidentelle',
    presentIllness: 'Piqûre aiguille souillée patient VIH+ ce matin lors pose voie veineuse urgence.',
    vitalSigns: {
      temperature: 36.6,
      bloodPressure: '110/70',
      heartRate: 95,
      respiratoryRate: 18,
    },
    physicalExam: 'Plaie punctiforme index droit. Pas de saignement actif.',
    assessment: 'Accident exposition sang - Risque VIH, VHB, VHC. Protocole post-exposition immédiat.',
    plan: 'Trithérapie préventive 28 jours. Sérologies J0, M1, M3, M6. Surveillance biologique.',
    notes: 'AES DÉCLARÉ - Protocole post-exposition démarré H+2',
    status: 'discharged',
    doctorId: 'DOC-004',
    doctorName: 'Dr. Mbuyi Médecine du Travail',
    facility: 'HGR Lubumbashi - Service Médecine Travail',
    createdAt: '2025-02-11T09:15:00Z',
    updatedAt: '2025-02-11T10:00:00Z',
  },
];

// ─── REALISTIC PRESCRIPTIONS LINKING ENCOUNTERS ────────────────

export const COMPREHENSIVE_PRESCRIPTIONS: Prescription[] = [
  // Mining worker - silicosis management
  {
    id: 'PRESC-001',
    prescriptionNumber: 'RX-2025-001',
    patientId: 'PAT-001',
    encounterId: 'ENC-001',
    doctorId: 'DOC-001',
    doctorName: 'Dr. Kasongo',
    prescriptionDate: '2025-02-08',
    status: 'partially_dispensed' as PrescriptionStatus,
    totalItems: 3,
    dispensedItems: 2,
    facility: 'Centre Médical Gécamines',
    notes: 'Traitement silicose débutante + hypertension. Suivi médecine travail requis.',
    createdAt: '2025-02-08T09:45:00Z',
    updatedAt: '2025-02-09T15:30:00Z',
    items: [
      {
        id: 'PRESC-ITEM-001',
        prescriptionId: 'PRESC-001',
        productId: 'PROD-004', // Amlodipine
        productName: 'Amlodipine 5mg',
        dosage: '5mg',
        frequency: 'once_daily',
        duration: '30 jours',
        quantity: 30,
        instructions: 'Prendre 1 comprimé le matin à jeun',
        status: 'fully_dispensed',
        dispensedQuantity: 30,
        dispensedDate: '2025-02-09',
        dispensedBy: 'Pharm. Mukendi',
      },
      {
        id: 'PRESC-ITEM-002',
        prescriptionId: 'PRESC-001',
        productId: 'PROD-005', // Bronchodilator
        productName: 'Salbutamol Inhalateur 100mcg',
        dosage: '100mcg/dose',
        frequency: 'as_needed',
        duration: 'selon besoin',
        quantity: 2,
        instructions: '2 bouffées si dyspnée - Max 8/jour',
        status: 'fully_dispensed',
        dispensedQuantity: 2,
        dispensedDate: '2025-02-09',
        dispensedBy: 'Pharm. Mukendi',
      },
      {
        id: 'PRESC-ITEM-003',
        prescriptionId: 'PRESC-001',
        productId: 'PROD-006', // Mucolytic
        productName: 'N-Acétylcystéine 600mg',
        dosage: '600mg',
        frequency: 'twice_daily',
        duration: '15 jours',
        quantity: 30,
        instructions: 'Diluer dans eau tiède - Matin et soir',
        status: 'pending',
        dispensedQuantity: 0,
      },
    ],
  },
  // Banking worker - carpal tunnel + anxiety
  {
    id: 'PRESC-002',
    prescriptionNumber: 'RX-2025-002',
    patientId: 'PAT-002',
    encounterId: 'ENC-002',
    doctorId: 'DOC-002',
    doctorName: 'Dr. Ngoy',
    prescriptionDate: '2025-02-10',
    status: 'pending' as PrescriptionStatus,
    totalItems: 3,
    dispensedItems: 0,
    facility: 'Clinique Rawbank',
    notes: 'Traitement syndrome canal carpien + anxiété professionnelle',
    createdAt: '2025-02-10T14:45:00Z',
    updatedAt: '2025-02-10T14:45:00Z',
    items: [
      {
        id: 'PRESC-ITEM-004',
        prescriptionId: 'PRESC-002',
        productId: 'PROD-002', // Ibuprofen
        productName: 'Ibuprofène 400mg',
        dosage: '400mg',
        frequency: 'three_times_daily',
        duration: '10 jours',
        quantity: 30,
        instructions: 'Avec repas - 3x/jour pendant 10 jours',
        status: 'pending',
        dispensedQuantity: 0,
      },
      {
        id: 'PRESC-ITEM-005',
        prescriptionId: 'PRESC-002',
        productId: 'PROD-007', // Sertraline
        productName: 'Sertraline 50mg',
        dosage: '50mg',
        frequency: 'once_daily',
        duration: '90 jours',
        quantity: 90,
        instructions: 'Le matin au réveil - Suivi psychiatre requis',
        status: 'pending',
        dispensedQuantity: 0,
      },
      {
        id: 'PRESC-ITEM-006',
        prescriptionId: 'PRESC-002',
        productId: 'PROD-008', // Wrist brace
        productName: 'Attelle Poignet Ergonomique',
        dosage: 'Taille M',
        frequency: 'continuous',
        duration: '4 semaines',
        quantity: 1,
        instructions: 'Porter 24h/24 pendant 4 semaines',
        status: 'pending',
        dispensedQuantity: 0,
      },
    ],
  },
  // Construction worker - accident du travail
  {
    id: 'PRESC-003',
    prescriptionNumber: 'RX-2025-003',
    patientId: 'PAT-003',
    encounterId: 'ENC-003',
    doctorId: 'DOC-003',
    doctorName: 'Dr. Mbala',
    prescriptionDate: '2025-02-05',
    status: 'fully_dispensed' as PrescriptionStatus,
    totalItems: 2,
    dispensedItems: 2,
    facility: 'Hôpital du Cinquantenaire',
    notes: 'Accident travail - Lombalgie post-traumatique',
    createdAt: '2025-02-05T12:30:00Z',
    updatedAt: '2025-02-06T10:15:00Z',
    items: [
      {
        id: 'PRESC-ITEM-007',
        prescriptionId: 'PRESC-003',
        productId: 'PROD-009', // Diclofenac
        productName: 'Diclofénac Gel 1%',
        dosage: '1% topique',
        frequency: 'three_times_daily',
        duration: '14 jours',
        quantity: 2,
        instructions: 'Application locale région lombaire 3x/jour',
        status: 'fully_dispensed',
        dispensedQuantity: 2,
        dispensedDate: '2025-02-06',
        dispensedBy: 'Pharm. Tshiala',
      },
      {
        id: 'PRESC-ITEM-008',
        prescriptionId: 'PRESC-003',
        productId: 'PROD-001', // Paracetamol
        productName: 'Paracétamol 1000mg',
        dosage: '1000mg',
        frequency: 'three_times_daily',
        duration: '7 jours',
        quantity: 21,
        instructions: 'Si douleur intense - Max 3g/jour',
        status: 'fully_dispensed',
        dispensedQuantity: 21,
        dispensedDate: '2025-02-06',
        dispensedBy: 'Pharm. Tshiala',
      },
    ],
  },
];

// ─── REALISTIC SALES LINKING PRESCRIPTIONS ─────────────────────

export const COMPREHENSIVE_SALES: Sale[] = [
  // Mining worker prescription fulfillment
  {
    id: 'SALE-001',
    receiptNumber: 'F-2025-001',
    date: '2025-02-09',
    time: '15:30',
    customerId: 'PAT-001',
    customerName: 'Kabamba Mutombo',
    prescriptionId: 'PRESC-001',
    items: [
      {
        id: 'SALE-ITEM-001',
        saleId: 'SALE-001',
        productId: 'PROD-004',
        productName: 'Amlodipine 5mg',
        sku: 'MED-AML-005',
        quantity: 30,
        unitPrice: 15.50,
        totalPrice: 465.00,
        discount: 0,
        category: 'Prescription',
      },
      {
        id: 'SALE-ITEM-002',
        saleId: 'SALE-001',
        productId: 'PROD-005',
        productName: 'Salbutamol Inhalateur 100mcg',
        sku: 'MED-SAL-100',
        quantity: 2,
        unitPrice: 85.00,
        totalPrice: 170.00,
        discount: 10.00, // Remise entreprise
        category: 'Prescription',
      },
    ],
    subtotal: 635.00,
    tax: 0,
    discount: 10.00,
    total: 625.00,
    paymentMethod: 'insurance' as PaymentMethod,
    paymentDetails: {
      insuranceProvider: 'Gécamines Medical Plan',
      copay: 62.50,
      covered: 562.50,
    },
    cashier: 'Pharm. Mukendi',
    facility: 'Pharmacie Gécamines',
    notes: 'Ordonnance médecine travail - Assurance entreprise',
    createdAt: '2025-02-09T15:30:00Z',
  },
  // Construction worker accident treatment
  {
    id: 'SALE-002',
    receiptNumber: 'F-2025-002',
    date: '2025-02-06',
    time: '10:15',
    customerId: 'PAT-003',
    customerName: 'Tshisekedi Ilunga',
    prescriptionId: 'PRESC-003',
    items: [
      {
        id: 'SALE-ITEM-003',
        saleId: 'SALE-002',
        productId: 'PROD-009',
        productName: 'Diclofénac Gel 1%',
        sku: 'MED-DIC-GEL',
        quantity: 2,
        unitPrice: 45.00,
        totalPrice: 90.00,
        discount: 0,
        category: 'Prescription',
      },
      {
        id: 'SALE-ITEM-004',
        saleId: 'SALE-002',
        productId: 'PROD-001',
        productName: 'Paracétamol 1000mg',
        sku: 'MED-PAR-1000',
        quantity: 21,
        unitPrice: 2.50,
        totalPrice: 52.50,
        discount: 0,
        category: 'Prescription',
      },
    ],
    subtotal: 142.50,
    tax: 0,
    discount: 0,
    total: 142.50,
    paymentMethod: 'workers_comp' as PaymentMethod,
    paymentDetails: {
      insuranceProvider: 'CNSS Accident Travail',
      claimNumber: 'AT-2025-0562',
      covered: 142.50,
    },
    cashier: 'Pharm. Tshiala',
    facility: 'Pharmacie du Cinquantenaire',
    notes: 'Accident travail - Prise en charge CNSS 100%',
    createdAt: '2025-02-06T10:15:00Z',
  },
  // Over-the-counter purchase
  {
    id: 'SALE-003',
    receiptNumber: 'F-2025-003',
    date: '2025-02-11',
    time: '14:20',
    customerId: 'PAT-005',
    customerName: 'Pongo Tshimanga',
    items: [
      {
        id: 'SALE-ITEM-005',
        saleId: 'SALE-003',
        productId: 'PROD-010',
        productName: 'Mélatonine 3mg',
        sku: 'SUP-MEL-003',
        quantity: 60,
        unitPrice: 1.25,
        totalPrice: 75.00,
        discount: 0,
        category: 'Supplement',
      },
      {
        id: 'SALE-ITEM-006',
        saleId: 'SALE-003',
        productId: 'PROD-011',
        productName: 'Lunettes Anti-Lumière Bleue',
        sku: 'ACC-BLU-001',
        quantity: 1,
        unitPrice: 125.00,
        totalPrice: 125.00,
        discount: 12.50, // Remise employé tech
        category: 'Accessory',
      },
    ],
    subtotal: 200.00,
    tax: 0,
    discount: 12.50,
    total: 187.50,
    paymentMethod: 'mobile_money' as PaymentMethod,
    paymentDetails: {
      provider: 'M-Pesa',
      transactionId: 'MP25021114201234',
    },
    cashier: 'Pharm. Kasongo',
    facility: 'Pharmacie Vodacom',
    notes: 'Achat préventif troubles sommeil',
    createdAt: '2025-02-11T14:20:00Z',
  },
];

export const ADDITIONAL_PRODUCTS: Product[] = [
  {
    id: 'PROD-001',
    organizationId: 'ORG-001',
    name: 'Paracétamol 500mg',
    genericName: 'Paracetamol',
    brandName: 'Doliprane',
    sku: 'PAR-500-TAB',
    barcode: '3401348890123',
    category: 'MEDICATION',
    subCategory: 'Analgesique',
    controlledSubstance: false,
    requiresPrescription: false,
    dosageForm: 'TABLET',
    strength: '500mg',
    unitOfMeasure: 'TABLET',
    packSize: 20,
    packType: 'blister',
    activeIngredients: ['Paracétamol 500mg'],
    manufacturer: 'Sanofi',
    indication: 'Douleur légère à modérée, fièvre',
    contraindication: 'Insuffisance hépatique sévère, hypersensibilité',
    sideEffects: 'Rares aux doses thérapeutiques, hépatotoxicité en cas de surdosage',
    dosageInstructions: '1-2 comprimés toutes les 6h, maximum 4g/jour',
    storageConditions: 'ROOM_TEMPERATURE',
    costPrice: 0.15,
    sellingPrice: 0.25,
    currency: 'USD',
    taxRate: 16,
    insuranceReimbursable: true,
    reorderLevel: 100,
    reorderQuantity: 500,
    minStockLevel: 50,
    maxStockLevel: 1000,
    safetyStockDays: 15,
    isActive: true,
    isDiscontinued: false,
    tags: ['otc', 'analgesic', 'antipyretic', 'common'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2025-02-09T15:30:00Z',
  },
  {
    id: 'PROD-002',
    organizationId: 'ORG-001',
    name: 'Amoxicilline 500mg',
    genericName: 'Amoxicillin trihydrate',
    brandName: 'Clamoxyl',
    sku: 'AMX-500-CAP',
    barcode: '3401597423691',
    category: 'MEDICATION',
    subCategory: 'Antibiotique',
    therapeuticClass: 'J01CA04',
    controlledSubstance: false,
    requiresPrescription: true,
    dosageForm: 'CAPSULE',
    strength: '500mg',
    unitOfMeasure: 'CAPSULE',
    packSize: 20,
    packType: 'blister',
    activeIngredients: ['Amoxicillin trihydrate 500mg'],
    manufacturer: 'GSK',
    indication: 'Infections bactériennes: pneumonie, bronchite, infections urinaires',
    contraindication: 'Allergie aux pénicillines, mononucléose infectieuse',
    sideEffects: 'Diarrhée, nausées, éruptions cutanées, réactions allergiques',
    dosageInstructions: '500mg toutes les 8h pendant 7-10 jours',
    storageConditions: 'ROOM_TEMPERATURE',
    warnings: 'Terminer le traitement complet même si amélioration',
    costPrice: 8.50,
    sellingPrice: 15.00,
    currency: 'USD',
    taxRate: 16,
    insuranceReimbursable: true,
    insuranceCode: 'ANT-AMX-500',
    reorderLevel: 30,
    reorderQuantity: 100,
    minStockLevel: 15,
    maxStockLevel: 200,
    safetyStockDays: 10,
    isActive: true,
    isDiscontinued: false,
    tags: ['antibiotic', 'penicillin', 'prescription'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2025-02-08T14:20:00Z',
  },
  {
    id: 'PROD-003',
    organizationId: 'ORG-001',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine besylate',
    brandName: 'Norvasc',
    sku: 'AML-005-TAB',
    barcode: '3401234567890',
    category: 'MEDICATION',
    subCategory: 'Antihypertenseur',
    therapeuticClass: 'C08CA01',
    controlledSubstance: false,
    requiresPrescription: true,
    dosageForm: 'TABLET',
    strength: '5mg',
    unitOfMeasure: 'TABLET',
    packSize: 30,
    packType: 'bottle',
    activeIngredients: ['Amlodipine besylate 5mg'],
    manufacturer: 'Pfizer',
    indication: 'Hypertension artérielle, angine de poitrine',
    contraindication: 'Choc cardiogénique, sténose aortique sévère',
    sideEffects: 'Œdème périphérique, fatigue, bouffées de chaleur, palpitations',
    dosageInstructions: '5-10mg une fois par jour, de préférence le matin',
    storageConditions: 'ROOM_TEMPERATURE',
    costPrice: 12.00,
    sellingPrice: 20.00,
    currency: 'USD',
    taxRate: 16,
    insuranceReimbursable: true,
    reorderLevel: 25,
    reorderQuantity: 75,
    minStockLevel: 10,
    maxStockLevel: 150,
    safetyStockDays: 20,
    isActive: true,
    isDiscontinued: false,
    tags: ['cardiovascular', 'chronic', 'prescription'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2025-02-08T16:45:00Z',
  },
  {
    id: 'PROD-004',
    organizationId: 'ORG-001',
    name: 'Salbutamol Inhalateur',
    genericName: 'Salbutamol sulfate',
    brandName: 'Ventolin',
    sku: 'SAL-100-INH',
    barcode: '3401348765432',
    category: 'MEDICATION',
    subCategory: 'Bronchodilatateur',
    therapeuticClass: 'R03AC02',
    controlledSubstance: false,
    requiresPrescription: true,
    dosageForm: 'INHALER',
    strength: '100mcg/dose',
    unitOfMeasure: 'UNIT',
    packSize: 1,
    packType: 'inhaler device',
    activeIngredients: ['Salbutamol sulfate 100mcg per actuation'],
    manufacturer: 'GSK',
    indication: 'Asthme, BPCO, bronchospasme',
    contraindication: 'Hypersensibilité au salbutamol',
    sideEffects: 'Tremblements, tachycardie, nervosité, céphalées',
    dosageInstructions: '1-2 bouffées selon besoin, maximum 8 bouffées/jour',
    storageConditions: 'ROOM_TEMPERATURE',
    warnings: 'Agiter avant utilisation. Amorcer si inutilisé >2 semaines',
    costPrice: 18.00,
    sellingPrice: 28.00,
    currency: 'USD',
    taxRate: 16,
    insuranceReimbursable: true,
    reorderLevel: 15,
    reorderQuantity: 40,
    minStockLevel: 8,
    maxStockLevel: 80,
    safetyStockDays: 15,
    isActive: true,
    isDiscontinued: false,
    tags: ['respiratory', 'bronchodilator', 'asthma'],
    createdAt: '2024-01-20T11:00:00Z',
    updatedAt: '2025-02-09T09:15:00Z',
  },
  {
    id: 'PROD-005',
    organizationId: 'ORG-001',
    name: 'Metformine 1000mg',
    genericName: 'Metformin HCl',
    brandName: 'Glucophage',
    sku: 'MET-1000-TAB',
    barcode: '3401456789012',
    category: 'MEDICATION',
    subCategory: 'Antidiabétique',
    therapeuticClass: 'A10BA02',
    controlledSubstance: false,
    requiresPrescription: true,
    dosageForm: 'TABLET',
    strength: '1000mg',
    unitOfMeasure: 'TABLET',
    packSize: 30,
    packType: 'bottle',
    activeIngredients: ['Metformin HCl 1000mg'],
    manufacturer: 'Merck',
    indication: 'Diabète de type 2, syndrome des ovaires polykystiques',
    contraindication: 'Insuffisance rénale sévère, acidose métabolique',
    sideEffects: 'Troubles digestifs, acidose lactique (rare), goût métallique',
    dosageInstructions: '1000mg 1-2 fois par jour avec les repas',
    storageConditions: 'ROOM_TEMPERATURE',
    warnings: 'Surveiller fonction rénale. Arrêter avant examens avec contraste',
    costPrice: 15.50,
    sellingPrice: 24.00,
    currency: 'USD',
    taxRate: 16,
    insuranceReimbursable: true,
    reorderLevel: 40,
    reorderQuantity: 120,
    minStockLevel: 20,
    maxStockLevel: 240,
    safetyStockDays: 25,
    isActive: true,
    isDiscontinued: false,
    tags: ['diabetes', 'chronic', 'prescription'],
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2025-02-10T12:30:00Z',
  },
  {
    id: 'PROD-006',
    organizationId: 'ORG-001',
    name: 'Ibuprofène 400mg',
    genericName: 'Ibuprofen',
    brandName: 'Advil',
    sku: 'IBU-400-TAB',
    barcode: '3401567890123',
    category: 'OTC',
    subCategory: 'Anti-inflammatoire',
    therapeuticClass: 'M01AE01',
    controlledSubstance: false,
    requiresPrescription: false,
    dosageForm: 'TABLET',
    strength: '400mg',
    unitOfMeasure: 'TABLET',
    packSize: 20,
    packType: 'blister',
    activeIngredients: ['Ibuprofen 400mg'],
    manufacturer: 'Pfizer',
    indication: 'Douleur, inflammation, fièvre',
    contraindication: 'Ulcère gastrique, insuffisance cardiaque sévère, grossesse (3e trimestre)',
    sideEffects: 'Troubles digestifs, rétention hydrosodée, réactions allergiques',
    dosageInstructions: '400mg toutes les 6-8h au maximum, avec les repas',
    storageConditions: 'ROOM_TEMPERATURE',
    warnings: 'Durée de traitement la plus courte possible',
    costPrice: 2.50,
    sellingPrice: 4.50,
    currency: 'USD',
    taxRate: 16,
    insuranceReimbursable: true,
    reorderLevel: 50,
    reorderQuantity: 200,
    minStockLevel: 25,
    maxStockLevel: 400,
    safetyStockDays: 12,
    isActive: true,
    isDiscontinued: false,
    tags: ['otc', 'anti-inflammatory', 'pain-relief'],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2025-02-11T08:20:00Z',
  }];
    id: 'PROD-004',
    organizationId: 'ORG-001',
    name: 'Amoxicilline',
    genericName: 'Amoxicillin',
    brandName: 'Augmentin',
    category: 'MEDICATION',
    dosageForm: 'CAPSULE',
    strength: '500mg',
    packSize: 12,
    unitOfMeasure: 'CAPSULE',
    sku: 'MED-AMX-500',
    barcode: '3401349990124',
    manufacturer: 'GSK',
    description: 'Antibiotique pénicilline',
    indication: 'Infections bactériennes',
    contraindications: 'Allergie pénicilline',
    sideEffects: 'Troubles digestifs, éruptions cutanées',
    dosageInstructions: '500mg 3 fois/jour pendant 7-10 jours',
    storageConditions: 'Conserver à température ambiante',
    prescriptionRequired: true,
    controlledSubstance: false,
    costPrice: 0.80,
    sellingPrice: 1.20,
    currency: 'USD',
    createdAt: '2024-01-10',
    updatedAt: '2025-02-05',
  },
  {
    id: 'PROD-005',
    organizationId: 'ORG-001',
    name: 'Ibuprofène',
    genericName: 'Ibuprofen',
    brandName: 'Advil',
    category: 'MEDICATION',
    dosageForm: 'TABLET',
    strength: '400mg',
    packSize: 30,
    unitOfMeasure: 'TABLET',
    sku: 'MED-IBU-400',
    barcode: '3401350990125',
    manufacturer: 'Pfizer',
    description: 'Anti-inflammatoire non stéroïdien',
    indication: 'Douleur, inflammation, fièvre',
    contraindications: 'Ulcère gastro-duodénal, insuffisance rénale',
    sideEffects: 'Troubles digestifs, céphalées',
    dosageInstructions: '400mg 2-3 fois/jour avec repas',
    storageConditions: 'Conserver à température ambiante',
    prescriptionRequired: false,
    controlledSubstance: false,
    costPrice: 0.12,
    sellingPrice: 0.20,
    currency: 'USD',
    createdAt: '2024-01-12',
    updatedAt: '2025-02-08',
  }
];

// ═══════════════════════════════════════════════════════════════
// SUPPLIERS
// ═══════════════════════════════════════════════════════════════

export const COMPREHENSIVE_SUPPLIERS = [
  {
    id: 'SUP-001',
    organizationId: 'ORG-001',
    name: 'PharmaDistrib Congo SARL',
    code: 'PDC001',
    contactPerson: 'Marie Lusamba',
    phone: '+243 81 123 4567',
    altPhone: '+243 99 123 4567',
    email: 'marie@pharmadistrib.cd',
    website: 'https://pharmadistrib.cd',
    address: 'Avenue des Cliniques 45',
    city: 'Kinshasa',
    country: 'RDC',
    taxId: 'A1708404F',
    licenseNumber: 'PHAR-DIST-001',
    paymentTerms: 'NET_30' as any,
    creditLimit: 50000,
    currentBalance: 12500,
    currency: 'USD',
    bankName: 'Banque Commerciale du Congo',
    bankAccountNumber: '001-123456789',
    rating: 4.5,
    leadTimeDays: 7,
    isActive: true,
    notes: 'Fournisseur principal pour médicaments de base et équipements médicaux',
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2025-02-01T00:00:00Z'
  },
  {
    id: 'SUP-002',
    organizationId: 'ORG-001',
    name: 'Laboratoires Sanofi RDC',
    code: 'SNF001',
    contactPerson: 'Dr. Jean Kapanda',
    phone: '+243 82 234 5678',
    email: 'j.kapanda@sanofi.cd',
    website: 'https://sanofi.cd',
    address: 'Boulevard du 30 Juin 120',
    city: 'Lubumbashi',
    country: 'RDC',
    taxId: 'A1804567G',
    licenseNumber: 'LAB-001',
    paymentTerms: 'NET_15' as any,
    creditLimit: 75000,
    currentBalance: 8900,
    currency: 'USD',
    bankName: 'Rawbank',
    bankAccountNumber: '002-987654321',
    rating: 4.8,
    leadTimeDays: 5,
    isActive: true,
    notes: 'Laboratoire pharmaceutique, produits de qualité',
    createdAt: '2023-02-20T00:00:00Z',
    updatedAt: '2025-01-28T00:00:00Z'
  },
  {
    id: 'SUP-003',
    organizationId: 'ORG-001',
    name: 'GSK Central Africa',
    code: 'GSK001',
    contactPerson: 'Sarah Mbuyi',
    phone: '+243 85 345 6789',
    email: 'sarah.mbuyi@gsk.com',
    website: 'https://gsk.com',
    address: 'Avenue de l\'Université 78',
    city: 'Kinshasa',
    country: 'RDC',
    taxId: 'A1903456H',
    licenseNumber: 'INT-PHAR-003',
    paymentTerms: 'NET_30' as any,
    creditLimit: 100000,
    currentBalance: 25600,
    currency: 'USD',
    bankName: 'Ecobank',
    bankAccountNumber: '003-456789123',
    rating: 4.7,
    leadTimeDays: 10,
    isActive: true,
    notes: 'Fournisseur international, antibiotiques et vaccins',
    createdAt: '2023-03-10T00:00:00Z',
    updatedAt: '2025-02-05T00:00:00Z'
  }
];

// ═══════════════════════════════════════════════════════════════
// INVENTORY ITEMS
// ═══════════════════════════════════════════════════════════════

export const COMPREHENSIVE_INVENTORY = [
  {
    id: 'INV-001',
    productId: 'PROD-001',
    facilityId: 'FAC-001',
    locationId: 'LOC-MAIN-001',
    currentStock: 180, // Main stockLevel tracking
    reservedStock: 30,
    availableStock: 150,
    reorderPoint: 50,
    maximumStock: 500,
    unitCost: 0.45,
    currency: 'USD',
    lastRestockDate: '2025-01-15T00:00:00Z',
    lastStockCount: '2025-02-01T00:00:00Z',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-09T00:00:00Z'
  },
  {
    id: 'INV-002',
    productId: 'PROD-002',
    facilityId: 'FAC-001',
    locationId: 'LOC-REFRIG-001',
    currentStock: 45,
    reservedStock: 5,
    availableStock: 40,
    reorderPoint: 20,
    maximumStock: 100,
    unitCost: 11.50,
    currency: 'USD',
    lastRestockDate: '2025-01-20T00:00:00Z',
    lastStockCount: '2025-02-01T00:00:00Z',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-09T00:00:00Z'
  },
  {
    id: 'INV-003',
    productId: 'PROD-003',
    facilityId: 'FAC-001',
    locationId: 'LOC-MAIN-001',
    currentStock: 950,
    reservedStock: 100,
    availableStock: 850,
    reorderPoint: 200,
    maximumStock: 2000,
    unitCost: 0.15,
    currency: 'USD',
    lastRestockDate: '2025-02-01T00:00:00Z',
    lastStockCount: '2025-02-01T00:00:00Z',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-09T00:00:00Z'
  },
  {
    id: 'INV-004',
    productId: 'PROD-004',
    facilityId: 'FAC-001',
    locationId: 'LOC-SECURE-001',
    currentStock: 120,
    reservedStock: 36,
    availableStock: 84,
    reorderPoint: 30,
    maximumStock: 300,
    unitCost: 0.80,
    currency: 'USD',
    lastRestockDate: '2025-01-25T00:00:00Z',
    lastStockCount: '2025-02-01T00:00:00Z',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-09T00:00:00Z'
  },
  {
    id: 'INV-005',
    productId: 'PROD-005',
    facilityId: 'FAC-001',
    locationId: 'LOC-MAIN-001',
    currentStock: 480,
    reservedStock: 60,
    availableStock: 420,
    reorderPoint: 150,
    maximumStock: 1000,
    unitCost: 0.12,
    currency: 'USD',
    lastRestockDate: '2025-01-28T00:00:00Z',
    lastStockCount: '2025-02-01T00:00:00Z',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-09T00:00:00Z'
  }
];

// ═══════════════════════════════════════════════════════════════
// PURCHASE ORDERS
// ═══════════════════════════════════════════════════════════════

export const COMPREHENSIVE_PURCHASE_ORDERS = [
  {
    id: 'PO-001',
    organizationId: 'ORG-001',
    supplierId: 'SUP-001',
    orderNumber: 'PO-2025-001',
    facilityId: 'FAC-001',
    orderDate: '2025-01-10T00:00:00Z',
    expectedDeliveryDate: '2025-01-17T00:00:00Z',
    actualDeliveryDate: '2025-01-15T00:00:00Z',
    status: 'DELIVERED' as any,
    totalAmount: 2450.00,
    currency: 'USD',
    paymentTerms: 'NET_30' as any,
    notes: 'Commande mensuelle de base',
    orderedBy: 'USER-002',
    approvedBy: 'USER-001',
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2025-01-15T14:30:00Z'
  },
  {
    id: 'PO-002',
    organizationId: 'ORG-001',
    supplierId: 'SUP-002',
    orderNumber: 'PO-2025-002',
    facilityId: 'FAC-001',
    orderDate: '2025-01-20T00:00:00Z',
    expectedDeliveryDate: '2025-01-25T00:00:00Z',
    status: 'PENDING_DELIVERY' as any,
    totalAmount: 1890.00,
    currency: 'USD',
    paymentTerms: 'NET_15' as any,
    notes: 'Réapprovisionnement Sanofi',
    orderedBy: 'USER-002',
    approvedBy: 'USER-001',
    createdAt: '2025-01-20T10:15:00Z',
    updatedAt: '2025-01-20T10:15:00Z'
  }
];

// ═══════════════════════════════════════════════════════════════
// STOCK MOVEMENTS
// ═══════════════════════════════════════════════════════════════

export const COMPREHENSIVE_STOCK_MOVEMENTS = [
  {
    id: 'SM-001',
    organizationId: 'ORG-001',
    inventoryItemId: 'INV-001',
    productId: 'PROD-001',
    movementType: 'PURCHASE_RECEIPT' as any,
    direction: 'IN' as any,
    quantity: 200,
    unitCost: 0.45,
    totalCost: 90.00,
    previousBalance: 10,
    newBalance: 210,
    referenceType: 'PURCHASE_ORDER' as any,
    referenceId: 'PO-001',
    referenceNumber: 'PO-2025-001',
    performedBy: 'USER-002',
    movementDate: '2025-01-15T14:30:00Z',
    reason: 'Réception commande fournisseur',
    createdAt: '2025-01-15T14:30:00Z'
  },
  {
    id: 'SM-002',
    organizationId: 'ORG-001',
    inventoryItemId: 'INV-001',
    productId: 'PROD-001',
    movementType: 'PRESCRIPTION' as any,
    direction: 'OUT' as any,
    quantity: 30,
    unitCost: 0.45,
    totalCost: 13.50,
    previousBalance: 210,
    newBalance: 180,
    referenceType: 'PRESCRIPTION' as any,
    referenceId: 'RX-001',
    referenceNumber: 'RX-2025-001',
    performedBy: 'USER-003',
    movementDate: '2025-02-10T10:00:00Z',
    reason: 'Délivrance prescription',
    createdAt: '2025-02-10T10:00:00Z'
  },
  {
    id: 'SM-003',
    organizationId: 'ORG-001',
    inventoryItemId: 'INV-003',
    productId: 'PROD-003',
    movementType: 'SALE' as any,
    direction: 'OUT' as any,
    quantity: 20,
    unitCost: 0.15,
    totalCost: 3.00,
    previousBalance: 970,
    newBalance: 950,
    referenceType: 'SALE' as any,
    referenceId: 'SALE-003',
    referenceNumber: 'V-0043',
    performedBy: 'USER-003',
    movementDate: '2025-02-09T15:30:00Z',
    reason: 'Vente au comptoir',
    createdAt: '2025-02-09T15:30:00Z'
  }
];