# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text="Nom d'utilisateur au moment de l'action", max_length=150, verbose_name="Nom d'utilisateur")),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email utilisateur')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Agent utilisateur')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('LOGIN_FAILED', 'Échec de connexion'), ('VIEW', 'Consultation'), ('DOWNLOAD', 'Téléchargement'), ('UPLOAD', 'Téléversement'), ('PRINT', 'Impression'), ('EXPORT', 'Exportation'), ('IMPORT', 'Importation'), ('DISPENSE', 'Dispensation'), ('SALE', 'Vente'), ('REFUND', 'Remboursement'), ('VOID', 'Annulation'), ('STOCK_ADJUSTMENT', 'Ajustement de stock'), ('INVENTORY_COUNT', 'Comptage inventaire'), ('PRICE_CHANGE', 'Changement de prix'), ('PERMISSION_CHANGE', 'Changement de permission'), ('PRESCRIPTION_RECEIVE', 'Réception ordonnance'), ('PRESCRIPTION_VALIDATE', 'Validation ordonnance'), ('PRESCRIPTION_REJECT', 'Rejet ordonnance'), ('SUPPLIER_ORDER', 'Commande fournisseur'), ('INVENTORY_RECEIVE', 'Réception marchandise'), ('BATCH_EXPIRE', 'Expiration lot')], max_length=50, verbose_name='Action')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20, verbose_name='Sévérité')),
                ('description', models.TextField(help_text="Description détaillée de l'action", verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, help_text="Représentation textuelle de l'objet au moment de l'action", max_length=255, verbose_name='Représentation objet')),
                ('old_values', models.JSONField(blank=True, help_text='Valeurs avant modification (JSON)', null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, help_text='Valeurs après modification (JSON)', null=True, verbose_name='Nouvelles valeurs')),
                ('module', models.CharField(blank=True, help_text="Module/app où l'action a eu lieu", max_length=100, verbose_name='Module')),
                ('view_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la vue')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Méthode HTTP')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin de la requête')),
                ('additional_data', models.JSONField(blank=True, help_text='Informations contextuelles supplémentaires (JSON)', null=True, verbose_name='Données supplémentaires')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text="Durée de l'opération en millisecondes", null=True, verbose_name='Durée (ms)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'objet")),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'ordonnance")),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU produit')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Nom produit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant')),
                ('patient_id', models.CharField(blank=True, help_text='ID anonymisé du patient', max_length=50, verbose_name='ID Patient')),
                ('doctor_name', models.CharField(blank=True, max_length=255, verbose_name='Nom médecin')),
                ('sale_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de vente')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Nom fournisseur')),
                ('requires_verification', models.BooleanField(default=False, verbose_name='Nécessite vérification')),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Horodatage vérification')),
                ('audit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audit.auditlog', verbose_name="Journal d'audit")),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pharmacy_audits', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': "Journal d'audit pharmacie",
                'verbose_name_plural': "Journaux d'audit pharmacie",
                'db_table': 'pharmacy_audit_log',
                'ordering': ['-audit_log__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('total_actions', models.PositiveIntegerField(default=0, verbose_name='Total actions')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de connexions')),
                ('failed_login_count', models.PositiveIntegerField(default=0, verbose_name='Échecs de connexion')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('prescriptions_dispensed', models.PositiveIntegerField(default=0, verbose_name='Ordonnances dispensées')),
                ('inventory_changes', models.PositiveIntegerField(default=0, verbose_name='Changements inventaire')),
                ('critical_actions', models.PositiveIntegerField(default=0, verbose_name='Actions critiques')),
                ('high_severity_actions', models.PositiveIntegerField(default=0, verbose_name='Actions haute sévérité')),
                ('failed_actions', models.PositiveIntegerField(default=0, verbose_name='Actions échouées')),
                ('active_users_count', models.PositiveIntegerField(default=0, verbose_name='Utilisateurs actifs')),
                ('unique_ips_count', models.PositiveIntegerField(default=0, verbose_name='IPs uniques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Résumé journal d'audit",
                'verbose_name_plural': "Résumés journaux d'audit",
                'db_table': 'audit_log_summary',
                'ordering': ['-date'],
                'unique_together': {('date', 'organization')},
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_log_user_id_835db7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_log_action_09d227_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_log_content_10f046_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='audit_log_organiz_1cfd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'timestamp'], name='audit_log_severit_917ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['success', 'timestamp'], name='audit_log_success_e4fe21_idx'),
        ),
    ]
