# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du fournisseur', max_length=200)),
                ('code', models.CharField(help_text='Code interne du fournisseur', max_length=50)),
                ('contact_person', models.CharField(help_text='Personne de contact', max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Numéro de téléphone principal', max_length=128, region=None)),
                ('alt_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numéro de téléphone alternatif', max_length=128, region=None)),
                ('email', models.EmailField(blank=True, help_text='Adresse e-mail', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Site web')),
                ('address', models.TextField(help_text='Adresse complète')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Congo (RDC)', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=100)),
                ('license_number', models.CharField(blank=True, help_text='Numéro de licence de distribution pharmaceutique', max_length=100)),
                ('payment_terms', models.CharField(choices=[('CASH_ON_DELIVERY', 'Paiement à la livraison'), ('NET_7', 'Net 7 jours'), ('NET_15', 'Net 15 jours'), ('NET_30', 'Net 30 jours'), ('NET_60', 'Net 60 jours'), ('NET_90', 'Net 90 jours'), ('PREPAID', 'Prépayé'), ('CREDIT', 'Crédit')], default='NET_30', help_text='Conditions de paiement', max_length=50)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Limite de crédit', max_digits=12, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Solde actuel avec le fournisseur', max_digits=12)),
                ('currency', models.CharField(default='CDF', help_text='Devise', max_length=3)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Note qualité du fournisseur (1-5)')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Délai de livraison moyen en jours')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'suppliers',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Contact Fournisseur',
                'verbose_name_plural': 'Contacts Fournisseur',
                'db_table': 'supplier_contacts',
            },
        ),
    ]
