# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('other', 'Autre')], max_length=10)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Hong Kong', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.JSONField(default=list, help_text='Allergies connues')),
                ('chronic_conditions', models.JSONField(default=list, help_text='Conditions chroniques')),
                ('current_medications', models.JSONField(default=list, help_text='Médicaments actifs')),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('patient_number', models.CharField(max_length=20, unique=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('deceased', 'Décédé')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
