# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Numéro de téléphone (identifiant de connexion)', max_length=128, region=None, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('primary_role', models.CharField(choices=[('admin', 'Super Administrateur'), ('hospital_admin', 'Administrateur Hospitalier'), ('pharmacy_admin', 'Administrateur Pharmacie'), ('doctor', 'Médecin'), ('nurse', 'Infirmier/ière'), ('pharmacist', 'Pharmacien'), ('pharmacy_tech', 'Technicien Pharmacie'), ('receptionist', 'Réceptionniste'), ('lab_technician', 'Technicien Laboratoire'), ('cashier', 'Caissier/ière'), ('inventory_manager', 'Gestionnaire Inventaire')], help_text='Rôle du personnel', max_length=50)),
                ('department', models.CharField(blank=True, help_text='Affectation du département', max_length=100)),
                ('employee_id', models.CharField(blank=True, help_text="Numéro d'employé interne", max_length=50)),
                ('professional_license', models.CharField(blank=True, help_text='Numéro de licence médicale/pharmaceutique', max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicateur de compte actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées JSON extensibles')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('manage_users', 'Gérer les Utilisateurs'), ('view_patients', 'Voir les Patients'), ('manage_patients', 'Gérer les Patients'), ('prescribe_medication', 'Prescrire des Médicaments'), ('dispense_medication', 'Dispenser des Médicaments'), ('manage_inventory', "Gérer l'Inventaire"), ('view_reports', 'Voir les Rapports'), ('manage_billing', 'Gérer la Facturation'), ('manage_appointments', 'Gérer les Rendez-vous'), ('access_lab_results', 'Accéder aux Résultats Lab'), ('manage_system_settings', 'Gérer Paramètres Système'), ('manage_licenses', 'Gérer les Licences'), ('view_analytics', 'Voir les Analyses'), ('manage_suppliers', 'Gérer les Fournisseurs'), ('access_pos', 'Accéder au POS'), ('manage_prescriptions', 'Gérer les Prescriptions'), ('access_medical_records', 'Accéder Dossiers Médicaux'), ('manage_wards', 'Gérer les Services'), ('view_financial_reports', 'Voir Rapports Financiers')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Utilisateur',
                'verbose_name_plural': 'Permissions Utilisateur',
                'db_table': 'user_permissions',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
