# Generated by Django 4.2.28 on 2026-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userpermission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_role',
            field=models.CharField(choices=[('admin', 'Super Administrateur'), ('hospital_admin', 'Administrateur Hospitalier'), ('pharmacy_admin', 'Administrateur Pharmacie'), ('doctor', 'Médecin'), ('nurse', 'Infirmier/ière'), ('pharmacist', 'Pharmacien'), ('pharmacy_tech', 'Technicien Pharmacie'), ('receptionist', 'Réceptionniste'), ('lab_technician', 'Technicien Laboratoire'), ('cashier', 'Caissier/ière'), ('inventory_manager', 'Gestionnaire Inventaire'), ('ohs_manager', 'Responsable OHS'), ('ohs_officer', 'Agent OHS'), ('occupational_doctor', 'Médecin du Travail')], help_text='Rôle du personnel', max_length=50),
        ),
    ]
