# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.CharField(blank=True, help_text='Référence consultation', max_length=100)),
                ('facility_id', models.CharField(help_text='Établissement prescripteur', max_length=100)),
                ('prescription_number', models.CharField(help_text="Numéro d'ordonnance auto-généré", max_length=50, unique=True)),
                ('date', models.DateField(help_text='Date de prescription')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partially_dispensed', 'Partiellement dispensé'), ('fully_dispensed', 'Complètement dispensé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=50)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnostic associé')),
                ('instructions', models.TextField(blank=True, help_text='Instructions générales')),
                ('valid_until', models.DateField(blank=True, help_text="Date d'expiration", null=True)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Nombre total de médicaments')),
                ('items_dispensed', models.PositiveIntegerField(default=0, help_text='Articles complètement dispensés')),
                ('is_complete', models.BooleanField(default=False, help_text='Tous les articles dispensés')),
                ('allergies_checked', models.BooleanField(default=False, help_text='Allergies vérifiées')),
                ('interactions_checked', models.BooleanField(default=False, help_text='Interactions médicamenteuses vérifiées')),
                ('clinical_notes', models.TextField(blank=True, help_text='Notes cliniques spéciales')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données extensibles')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Médecin prescripteur', on_delete=django.db.models.deletion.CASCADE, related_name='written_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('CLINICAL', 'Note clinique'), ('DISPENSING', 'Note de dispensation'), ('COMMUNICATION', 'Communication'), ('QUALITY', 'Contrôle qualité'), ('INSURANCE', 'Assurance'), ('COMPLIANCE', 'Conformité'), ('OTHER', 'Autre')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_visible_to_patient', models.BooleanField(default=False)),
                ('is_visible_to_doctor', models.BooleanField(default=True)),
                ('is_visible_to_pharmacist', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normal'), ('HIGH', 'Élevée'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_notes', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Note Ordonnance',
                'verbose_name_plural': 'Notes Ordonnance',
                'db_table': 'prescription_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text="Image de l'ordonnance", upload_to='prescriptions/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('ocr_text', models.TextField(blank=True, help_text='Texte extrait par OCR')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prescriptions.prescription')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Ordonnance',
                'verbose_name_plural': 'Images Ordonnance',
                'db_table': 'prescription_images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(help_text='Nom du médicament (texte libre)', max_length=200)),
                ('generic_name', models.CharField(blank=True, help_text='Nom générique DCI', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage (ex: 500mg)', max_length=100)),
                ('strength', models.CharField(blank=True, help_text='Concentration (ex: 500mg/comprimé)', max_length=100)),
                ('dosage_form', models.CharField(blank=True, choices=[('tablet', 'Comprimé'), ('capsule', 'Gélule'), ('syrup', 'Sirop'), ('suspension', 'Suspension'), ('injection', 'Injectable'), ('cream', 'Crème'), ('ointment', 'Pommade'), ('gel', 'Gel'), ('drops', 'Gouttes'), ('inhaler', 'Inhalateur'), ('suppository', 'Suppositoire'), ('powder', 'Poudre'), ('solution', 'Solution'), ('spray', 'Spray'), ('patch', 'Timbre'), ('lozenge', 'Pastille'), ('other', 'Autre')], help_text='Forme galénique', max_length=50)),
                ('frequency', models.CharField(help_text='Fréquence (TDS, BD, PRN, etc.)', max_length=50)),
                ('duration', models.CharField(help_text='Durée (7 jours, 2 semaines, 1 mois)', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantité totale à dispenser', validators=[django.core.validators.MinValueValidator(1)])),
                ('route', models.CharField(choices=[('oral', 'Oral (PO)'), ('sublingual', 'Sublingual (SL)'), ('topical', 'Topique'), ('transdermal', 'Transdermique'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('nasal', 'Nasal'), ('inhalation', 'Inhalation'), ('intramuscular', 'Intramusculaire (IM)'), ('intravenous', 'Intraveineux (IV)'), ('subcutaneous', 'Sous-cutané (SC)'), ('intradermal', 'Intradermique'), ('ophthalmic', 'Ophtalmique'), ('otic', 'Auriculaire'), ('other', 'Autre')], help_text="Voie d'administration", max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Instructions spéciales (prendre après repas, appliquer sur zone affectée)')),
                ('quantity_dispensed', models.PositiveIntegerField(default=0, help_text='Quantité réellement dispensée')),
                ('quantity_remaining', models.PositiveIntegerField(default=0, help_text='Quantité restante à dispenser')),
                ('batches_used', models.JSONField(blank=True, default=list, help_text='IDs des lots utilisés pour la dispensation')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire lors de la dispensation', max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Coût total pour cet article', max_digits=12, null=True)),
                ('currency', models.CharField(default='CDF', max_length=3)),
                ('dispensed_date', models.DateTimeField(blank=True, help_text='Date et heure de dispensation', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partially_dispensed', 'Partiellement dispensé'), ('fully_dispensed', 'Dispensé'), ('out_of_stock', 'Rupture de stock'), ('discontinued', 'Discontinué'), ('cancelled', 'Annulé'), ('substituted', 'Substitué')], default='pending', max_length=50)),
                ('is_substitution_allowed', models.BooleanField(default=True, help_text='Substitution générique autorisée')),
                ('is_controlled', models.BooleanField(default=False, help_text='Substance contrôlée')),
                ('requires_counseling', models.BooleanField(default=False, help_text='Conseil pharmaceutique spécial requis')),
                ('pharmacist_notes', models.TextField(blank=True, help_text='Notes de dispensation du pharmacien')),
                ('patient_counseling', models.TextField(blank=True, help_text='Informations données au patient')),
                ('substitution_reason', models.TextField(blank=True, help_text='Raison de la substitution si applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescription_items', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(blank=True, help_text='Pharmacien qui a dispensé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescription_items', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
                ('product', models.ForeignKey(blank=True, help_text='Produit correspondant trouvé lors de la dispensation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prescription_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Ordonnance',
                'verbose_name_plural': 'Articles Ordonnance',
                'db_table': 'prescription_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='prescriptio_status_ae5908_idx'), models.Index(fields=['medication_name'], name='prescriptio_medicat_7d895c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='prescriptio_prescri_b8a9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'created_at'], name='prescriptio_patient_50dfd5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'created_at'], name='prescriptio_doctor__2c554b_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['date'], name='prescriptio_date_d2a5df_idx'),
        ),
    ]
