# Generated by Django 4.2.28 on 2026-02-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='encounter_id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='Consultation associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='hospital.hospitalencounter'),
        ),
    ]
