"""
Reports Admin Configuration
"""

from django.contrib import admin
from .models import SavedReport, ReportExport


@admin.register(SavedReport)
class SavedReportAdmin(admin.ModelAdmin):
    list_display = ['name', 'report_type', 'frequency', 'is_active', 'created_at']
    list_filter = ['report_type', 'frequency', 'is_active', 'created_at']
    search_fields = ['name', 'report_type']
    readonly_fields = ['id', 'created_at', 'updated_at']
    fieldsets = (
        ('Report Information', {
            'fields': ('id', 'name', 'report_type', 'organization')
        }),
        ('Schedule & Recipients', {
            'fields': ('frequency', 'recipients')
        }),
        ('Configuration', {
            'fields': ('filters', 'is_active')
        }),
        ('Audit', {
            'fields': ('created_by', 'created_at', 'updated_at'),
            'classes': ('collapse',)
        }),
    )


@admin.register(ReportExport)
class ReportExportAdmin(admin.ModelAdmin):
    list_display = ['report', 'export_format', 'generated_by', 'generated_at', 'download_count']
    list_filter = ['export_format', 'generated_at']
    search_fields = ['report__name']
    readonly_fields = ['id', 'generated_at', 'download_count']
    fieldsets = (
        ('Export Information', {
            'fields': ('id', 'report', 'export_format', 'file_path')
        }),
        ('Generated By', {
            'fields': ('generated_by', 'generated_at')
        }),
        ('Status', {
            'fields': ('download_count', 'expires_at')
        }),
    )
