# Generated by Django 6.0.3 on 2026-04-21 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0002_update_encounter_relationship'),
        ('sales', '0002_sale_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selling_unit',
            field=models.CharField(choices=[('BOX', 'Boîte'), ('BLISTER', 'Plaquette'), ('UNIT', 'Unité')], default='BOX', help_text='Unité de vente', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='base_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantité convertie en unités de base pour le stock'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='selling_unit',
            field=models.CharField(choices=[('BOX', 'Boîte'), ('BLISTER', 'Plaquette'), ('UNIT', 'Unité')], default='BOX', help_text='Unité de vente: boîte, plaquette ou unité', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'created_at'], name='sales_organiz_000bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status'], name='sales_organiz_ab90bf_idx'),
        ),
    ]
