# Generated by Django 4.2.28 on 2026-02-17 12:29

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom de l'organisation", max_length=200)),
                ('type', models.CharField(choices=[('hospital', 'Hôpital'), ('pharmacy', 'Pharmacie'), ('clinic', 'Clinique'), ('laboratory', 'Laboratoire'), ('health_center', 'Centre de Santé')], help_text="Type d'organisation", max_length=50)),
                ('registration_number', models.CharField(help_text="Numéro d'enregistrement gouvernemental", max_length=100, unique=True)),
                ('license_number', models.CharField(blank=True, help_text="Numéro de licence d'exploitation", max_length=100)),
                ('address', models.TextField(help_text='Adresse complète')),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Hong Kong', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Numéro de téléphone principal', max_length=128, region=None)),
                ('email', models.EmailField(help_text='Adresse e-mail principale', max_length=254)),
                ('website', models.URLField(blank=True, help_text="Site web de l'organisation")),
                ('director_name', models.CharField(help_text='Nom du directeur/administrateur', max_length=200)),
                ('director_license', models.CharField(blank=True, help_text='Licence professionnelle du directeur', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional organization data')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
